namespace MinimalApiTest.Application.Contracts.Requisitions.Responses;

public class RequisitionDetailedResponse
{
    public long OrderId { get; set; }
    public long? SupplierId { get; set; }
    public string? Special { get; set; }
    public long? RequestedBy { get; set; }
    public string? RequestedFor { get; set; }
    public bool? Urgent { get; set; }
    public string? OrderStatus { get; set; }
    public long? DeliveryAddressId { get; set; }
    public DateTime? OrderDate { get; set; }
    public bool? Deleted { get; set; }
    public bool? SentToSage { get; set; }
    public bool? Cancelled { get; set; }
    public long? InvoiceAddressId { get; set; }
    public long? SageOrderId { get; set; }
    public long? SageDatabaseId { get; set; }
    public DateTime? DeliveryDate { get; set; }
    public string? SupplierReference { get; set; }
    public string? Analysis1 { get; set; }
    public string? Analysis2 { get; set; }
    public string? Analysis3 { get; set; }
    public string? Analysis4 { get; set; }
    public string? Analysis5 { get; set; }
    public string? Analysis6 { get; set; }
    public string? Analysis7 { get; set; }
    public string? Analysis8 { get; set; }
    public string? Analysis9 { get; set; }
    public string? Analysis10 { get; set; }
    public string? Analysis11 { get; set; }
    public string? Analysis12 { get; set; }
    public string? Analysis13 { get; set; }
    public string? Analysis14 { get; set; }
    public string? Analysis15 { get; set; }
    public string? Analysis16 { get; set; }
    public string? Analysis17 { get; set; }
    public string? Analysis18 { get; set; }
    public string? Analysis19 { get; set; }
    public string? Analysis20 { get; set; }
    public decimal? OrderDiscount { get; set; }
    public string? SageDatabaseName { get; set; }
    public string? SupplierName { get; set; }
    public string? RequestedByName { get; set; }
    public string? DeliveryAddressName { get; set; }
    public decimal? NetValue { get; set; }
    public long? DepartmentId { get; set; }
    public string? PodocumentNo { get; set; }
    public bool? ConstructRelated { get; set; }
    public bool? Archived { get; set; }
    public string? UpdateStatus { get; set; }
    public DateTime? UpdatedDate { get; set; }
    public string? UpdatedUser { get; set; }
    public long? WarehouseId { get; set; }
    public decimal? ExchangeRate { get; set; }
    public string? CurrencySymbol { get; set; }
    public string? SupplierEmailAddress { get; set; }
    public string? SupplierContactName { get; set; }
    public string? SupplierTelephone { get; set; }
    public string? SupplierFax { get; set; }
    public bool? HasAttachments { get; set; }
    public bool? HasAnalysisValues { get; set; }
    public long? SystraderAnalysisValueId { get; set; }
    public bool? InternalOrder { get; set; }
    public string? DeliveryPostalName { get; set; }
    public string? DeliveryAddressLine1 { get; set; }
    public string? DeliveryAddressLine2 { get; set; }
    public string? DeliveryAddressLine3 { get; set; }
    public string? DeliveryAddressLine4 { get; set; }
    public string? DeliveryPostCode { get; set; }
    public string? InvoicePostalName { get; set; }
    public string? InvoiceAddressLine1 { get; set; }
    public string? InvoiceAddressLine2 { get; set; }
    public string? InvoiceAddressLine3 { get; set; }
    public string? InvoiceAddressLine4 { get; set; }
    public string? InvoicePostCode { get; set; }
    public string? DeliveryContactName { get; set; }
    public string? InvoiceContactName { get; set; }
    public string? DeliveryTelephoneNo { get; set; }
    public string? DeliveryFaxNo { get; set; }
    public string? InvoiceTelephoneNo { get; set; }
    public string? InvoiceFaxNo { get; set; }
    public bool? CheckForNewDocuments { get; set; }
    public bool? EmailSent { get; set; }
    public string? DocumentNoPrefix { get; set; }
    public string? AdditionalReference { get; set; }
    public DateTime? FullyApprovedDate { get; set; }
    public string? ErrorMessage { get; set; }
    public bool? Confidential { get; set; }
    public bool? MandatoryCustom1 { get; set; }
    public bool? MandatoryCustom2 { get; set; }
    public bool? MandatoryCustom3 { get; set; }
    public string? DeliveryAddressType { get; set; }
    public string? UrgentReason { get; set; }
    public bool? CallOff { get; set; }
    public DateTime? SubmittedDate { get; set; }
    public bool? OutOfHours { get; set; }
    public bool Printed { get; set; }
    public bool Mrporder { get; set; }
    public string? Hyperlink { get; set; }
    public string? MobileGuid { get; set; }
    public bool QuoteRequestPrinted { get; set; }
    public bool QuoteRequestEmailed { get; set; }
    public string? SpareText1 { get; set; }
    public string? SpareText2 { get; set; }
    public string? SpareText3 { get; set; }
    public DateTime? SpareDate1 { get; set; }
    public DateTime? SpareDate2 { get; set; }
    public DateTime? SpareDate3 { get; set; }
    public bool SpareBit1 { get; set; }
    public bool SpareBit2 { get; set; }
    public bool SpareBit3 { get; set; }
    public decimal? SpareNumber1 { get; set; }
    public decimal? SpareNumber2 { get; set; }
    public decimal? SpareNumber3 { get; set; }
    public long? DefaultProjectId { get; set; }
    public string? InvoiceCity { get; set; }
    public string? InvoiceCounty { get; set; }
    public long? ProjectRequisitionId { get; set; }
    public virtual IEnumerable<RequisitionLineResponse>? RequisitionLines { get; set; }
}

public class RequisitionLineResponse
{
    public long OrderLineId { get; set; }
    public long? OrderId { get; set; }
    public decimal? Quantity { get; set; }
    public string? Description { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal? Discount { get; set; }
    public long? AccountNumberId { get; set; }
    public bool? Deleted { get; set; }
    public long? WaitingForId { get; set; }
    public string? WaitingForApprovalType { get; set; }
    public string? LineStatus { get; set; }
    public bool? OverBudget { get; set; }
    public bool? SentToSage { get; set; }
    public decimal? SentToSageValue { get; set; }
    public decimal? TotalPrice { get; set; }
    public string? LineType { get; set; }
    public long? ProjectCodeId { get; set; }
    public long? ProjectItemId { get; set; }
    public long? ProjectPhaseId { get; set; }
    public long? ProjectStageId { get; set; }
    public long? ProjectSubStageId { get; set; }
    public long? ProjectVariationId { get; set; }
    public long? SageOrderLineId { get; set; }
    public int? LineStatusId { get; set; }
    public long? StockItemId { get; set; }
    public long? SageDatabaseId { get; set; }
    public string? ItemCode { get; set; }
    public long? TaxCodeId { get; set; }
    public long? WarehouseId { get; set; }
    public int? CurrentStep { get; set; }
    public long? ContractId { get; set; }
    public long? ContractItemId { get; set; }
    public decimal? QuantityReceived { get; set; }
    public DateTime? UpdatedDate { get; set; }
    public string? UpdatedUser { get; set; }
    public bool? ShowCommentOnSupplierDocs { get; set; }
    public string? PricingUnitDescription { get; set; }
    public string? BuyingUnitDescription { get; set; }
    public decimal? BuyingMultOfStockUnit { get; set; }
    public decimal? PricingMultOfStockUnit { get; set; }
    public DateTime? RequestedDeliveryDate { get; set; }
    public string? SupplierPartNo { get; set; }
    public bool? CustomRoute { get; set; }
    public long? CustomRouteId { get; set; }
    public string? RejectReason { get; set; }
    public long? CurrentStepApprovalCount { get; set; }
    public decimal? QuantityInvoiced { get; set; }
    public long? PccostItemId { get; set; }
    public bool? Submitted { get; set; }
    public long? ConstructVariationId { get; set; }
    public long? ConstructLineTypeId { get; set; }
    public long? LineNumber { get; set; }
    public bool? AmendedDescription { get; set; }
    public string? AmendedDescriptionText { get; set; }
    public long? PostedCostingDetailId { get; set; }
    public long? ConfirmationIntentType { get; set; }
    public decimal? MatchedExpenseLinesNetValue { get; set; }
    public string? ErrorMessage { get; set; }
    public string? IdentificationNumber { get; set; }
    public string? Analysis1 { get; set; }
    public string? Analysis2 { get; set; }
    public string? Analysis3 { get; set; }
    public string? Analysis4 { get; set; }
    public string? Analysis5 { get; set; }
    public string? Analysis6 { get; set; }
    public string? Analysis7 { get; set; }
    public string? Analysis8 { get; set; }
    public string? Analysis9 { get; set; }
    public string? Analysis10 { get; set; }
    public string? Analysis11 { get; set; }
    public string? Analysis12 { get; set; }
    public string? Analysis13 { get; set; }
    public string? Analysis14 { get; set; }
    public string? Analysis15 { get; set; }
    public string? Analysis16 { get; set; }
    public string? Analysis17 { get; set; }
    public string? Analysis18 { get; set; }
    public string? Analysis19 { get; set; }
    public string? Analysis20 { get; set; }
    public bool ResetRoute { get; set; }
    public string? MobileGuid { get; set; }
    public string? JobManager { get; set; }
    public long? PlannedPurchaseId { get; set; }
    public string? SpareText1 { get; set; }
    public string? SpareText2 { get; set; }
    public string? SpareText3 { get; set; }
    public DateTime? SpareDate1 { get; set; }
    public DateTime? SpareDate2 { get; set; }
    public DateTime? SpareDate3 { get; set; }
    public bool SpareBit1 { get; set; }
    public bool SpareBit2 { get; set; }
    public bool SpareBit3 { get; set; }
    public decimal? SpareNumber1 { get; set; }
    public decimal? SpareNumber2 { get; set; }
    public decimal? SpareNumber3 { get; set; }
    public long? ProjectRequisitionLineId { get; set; }
}

