using System;
using System.Collections.Generic;

namespace MinimalApiTest.Domain.SageModels
{
    public partial class SiconFixedAssetFieldValue
    {
        public long SiconFixedAssetFieldValuesId { get; set; }
        public long FixedAssetId { get; set; }
        public string? StringValue1 { get; set; }
        public string? StringValue2 { get; set; }
        public string? StringValue3 { get; set; }
        public string? StringValue4 { get; set; }
        public string? StringValue5 { get; set; }
        public string? StringValue6 { get; set; }
        public string? StringValue7 { get; set; }
        public string? StringValue8 { get; set; }
        public string? StringValue9 { get; set; }
        public string? StringValue10 { get; set; }
        public string? StringValue11 { get; set; }
        public string? StringValue12 { get; set; }
        public string? StringValue13 { get; set; }
        public string? StringValue14 { get; set; }
        public string? StringValue15 { get; set; }
        public string? StringValue16 { get; set; }
        public string? StringValue17 { get; set; }
        public string? StringValue18 { get; set; }
        public string? StringValue19 { get; set; }
        public string? StringValue20 { get; set; }
        public DateTime? DateValue1 { get; set; }
        public DateTime? DateValue2 { get; set; }
        public DateTime? DateValue3 { get; set; }
        public DateTime? DateValue4 { get; set; }
        public DateTime? DateValue5 { get; set; }
        public DateTime? DateValue6 { get; set; }
        public DateTime? DateValue7 { get; set; }
        public DateTime? DateValue8 { get; set; }
        public DateTime? DateValue9 { get; set; }
        public DateTime? DateValue10 { get; set; }
        public DateTime? DateValue11 { get; set; }
        public DateTime? DateValue12 { get; set; }
        public DateTime? DateValue13 { get; set; }
        public DateTime? DateValue14 { get; set; }
        public DateTime? DateValue15 { get; set; }
        public DateTime? DateValue16 { get; set; }
        public DateTime? DateValue17 { get; set; }
        public DateTime? DateValue18 { get; set; }
        public DateTime? DateValue19 { get; set; }
        public DateTime? DateValue20 { get; set; }
        public decimal? NumericValue1 { get; set; }
        public decimal? NumericValue2 { get; set; }
        public decimal? NumericValue3 { get; set; }
        public decimal? NumericValue4 { get; set; }
        public decimal? NumericValue5 { get; set; }
        public decimal? NumericValue6 { get; set; }
        public decimal? NumericValue7 { get; set; }
        public decimal? NumericValue8 { get; set; }
        public decimal? NumericValue9 { get; set; }
        public decimal? NumericValue10 { get; set; }
        public decimal? NumericValue11 { get; set; }
        public decimal? NumericValue12 { get; set; }
        public decimal? NumericValue13 { get; set; }
        public decimal? NumericValue14 { get; set; }
        public decimal? NumericValue15 { get; set; }
        public decimal? NumericValue16 { get; set; }
        public decimal? NumericValue17 { get; set; }
        public decimal? NumericValue18 { get; set; }
        public decimal? NumericValue19 { get; set; }
        public decimal? NumericValue20 { get; set; }
        public bool? BooleanValue1 { get; set; }
        public bool? BooleanValue2 { get; set; }
        public bool? BooleanValue3 { get; set; }
        public bool? BooleanValue4 { get; set; }
        public bool? BooleanValue5 { get; set; }
        public bool? BooleanValue6 { get; set; }
        public bool? BooleanValue7 { get; set; }
        public bool? BooleanValue8 { get; set; }
        public bool? BooleanValue9 { get; set; }
        public bool? BooleanValue10 { get; set; }
        public bool? BooleanValue11 { get; set; }
        public bool? BooleanValue12 { get; set; }
        public bool? BooleanValue13 { get; set; }
        public bool? BooleanValue14 { get; set; }
        public bool? BooleanValue15 { get; set; }
        public bool? BooleanValue16 { get; set; }
        public bool? BooleanValue17 { get; set; }
        public bool? BooleanValue18 { get; set; }
        public bool? BooleanValue19 { get; set; }
        public bool? BooleanValue20 { get; set; }
        public long? ForiegnKeyValue1 { get; set; }
        public long? ForiegnKeyValue2 { get; set; }
        public long? ForiegnKeyValue3 { get; set; }
        public long? ForiegnKeyValue4 { get; set; }
        public long? ForiegnKeyValue5 { get; set; }
        public long? ForiegnKeyValue6 { get; set; }
        public long? ForiegnKeyValue7 { get; set; }
        public long? ForiegnKeyValue8 { get; set; }
        public long? ForiegnKeyValue9 { get; set; }
        public long? ForiegnKeyValue10 { get; set; }
        public long? ForiegnKeyValue11 { get; set; }
        public long? ForiegnKeyValue12 { get; set; }
        public long? ForiegnKeyValue13 { get; set; }
        public long? ForiegnKeyValue14 { get; set; }
        public long? ForiegnKeyValue15 { get; set; }
        public long? ForiegnKeyValue16 { get; set; }
        public long? ForiegnKeyValue17 { get; set; }
        public long? ForiegnKeyValue18 { get; set; }
        public long? ForiegnKeyValue19 { get; set; }
        public long? ForiegnKeyValue20 { get; set; }
        public bool? BooleanValue21 { get; set; }
        public bool? BooleanValue22 { get; set; }
        public bool? BooleanValue23 { get; set; }
        public bool? BooleanValue24 { get; set; }
        public bool? BooleanValue25 { get; set; }
        public bool? BooleanValue26 { get; set; }
        public bool? BooleanValue27 { get; set; }
        public bool? BooleanValue28 { get; set; }
        public bool? BooleanValue29 { get; set; }
        public bool? BooleanValue30 { get; set; }
        public bool? BooleanValue31 { get; set; }
        public bool? BooleanValue32 { get; set; }
        public bool? BooleanValue33 { get; set; }
        public bool? BooleanValue34 { get; set; }
        public bool? BooleanValue35 { get; set; }
        public bool? BooleanValue36 { get; set; }
        public bool? BooleanValue37 { get; set; }
        public bool? BooleanValue38 { get; set; }
        public bool? BooleanValue39 { get; set; }
        public bool? BooleanValue40 { get; set; }
        public string? StringValue21 { get; set; }
        public string? StringValue22 { get; set; }
        public string? StringValue23 { get; set; }
        public string? StringValue24 { get; set; }
        public string? StringValue25 { get; set; }
        public string? StringValue26 { get; set; }
        public string? StringValue27 { get; set; }
        public string? StringValue28 { get; set; }
        public string? StringValue29 { get; set; }
        public string? StringValue30 { get; set; }
        public string? StringValue31 { get; set; }
        public string? StringValue32 { get; set; }
        public string? StringValue33 { get; set; }
        public string? StringValue34 { get; set; }
        public string? StringValue35 { get; set; }
        public string? StringValue36 { get; set; }
        public string? StringValue37 { get; set; }
        public string? StringValue38 { get; set; }
        public string? StringValue39 { get; set; }
        public string? StringValue40 { get; set; }
    }
}
