using System;
using System.Collections.Generic;

namespace MinimalApiTest.Domain.SageModels
{
    public partial class SiconFixedAsset
    {
        public long FixedAssetId { get; set; }
        public string? Code { get; set; }
        public string Name { get; set; } = null!;
        public string? Description { get; set; }
        public decimal? CostValue { get; set; }
        public decimal? RevaluationCostValue { get; set; }
        public decimal? LastDepreciationValue { get; set; }
        public DateTime? LastDepreciationDate { get; set; }
        public string? LastDepreciationPeriod { get; set; }
        public decimal? AccumulatedDepreciation { get; set; }
        public decimal? NetBookValue { get; set; }
        public long? DepreciationTypeId { get; set; }
        public decimal? ResidualValue { get; set; }
        public decimal? ExpectedLife { get; set; }
        public decimal? RevaluationExpectedLife { get; set; }
        public decimal? ExpectedLifeLeft { get; set; }
        public string WhenToDepreciate { get; set; } = null!;
        public decimal? DepreciationRate { get; set; }
        public long? FixedAssetNominalAccountId { get; set; }
        public long? PurchaseNominalAccountId { get; set; }
        public long? BalanceSheetNominalAccountId { get; set; }
        public long? ProfitAndLossNominalAccountId { get; set; }
        public decimal? InsuranceValue { get; set; }
        public string? SerialNumber { get; set; }
        public DateTime? DateOfPurchase { get; set; }
        public DateTime? CapitalisationDate { get; set; }
        public long? CategoryId { get; set; }
        public long? SubCategoryId { get; set; }
        public long? LocationId { get; set; }
        public long? EmployeeId { get; set; }
        public long? DefaultMaintainerId { get; set; }
        public long? PurchaseSupplierId { get; set; }
        public long? SiJcJobId { get; set; }
        public long? SiJcChdId { get; set; }
        public string? Pacode { get; set; }
        public long? InsuranceId { get; set; }
        public long? InsuranceCategoryId { get; set; }
        public string? DepreciationRateType { get; set; }
        public long? PurchaseInvoiceUrn { get; set; }
        public bool? Disposed { get; set; }
        public DateTime? DisposalDate { get; set; }
        public string? ReasonForDisposal { get; set; }
        public string? ReasonForRightOff { get; set; }
        public long? SalesInvoiceUrn { get; set; }
        public decimal? DisposalGrossValue { get; set; }
        public string? DisposalCustomer { get; set; }
        public string? Manufacturer { get; set; }
        public string? Model { get; set; }
        public long? Fastatus { get; set; }
        public bool NegativeAsset { get; set; }
        public bool IsFullyDepreciated { get; set; }
        public string? SpareText1 { get; set; }
        public string? SpareText2 { get; set; }
        public string? SpareText3 { get; set; }
        public decimal? SpareNumber1 { get; set; }
        public decimal? SpareNumber2 { get; set; }
        public decimal? SpareNumber3 { get; set; }
        public long? SiconFixedAssetTypeId { get; set; }
        public string? RegistrationNo { get; set; }
        public string? ChassisNo { get; set; }
        public string? FleetNo { get; set; }
        public DateTime? RegisteredDate { get; set; }
        public DateTime? RoadFundRenewalDate { get; set; }
        public DateTime? DateNextMot { get; set; }
        public string? NormalUserOfVehicle { get; set; }
        public DateTime? DateMileageLastChanged { get; set; }
        public string? MaintainedBy { get; set; }
        public string? MaintainedByPhoneNumber { get; set; }
        public DateTime? DateNextService { get; set; }
        public string? ServicingCostsToDate { get; set; }
        public long? VehicleExpectedLifeMiles { get; set; }
        public long? CurrentMileageBusiness { get; set; }
        public long? CurrentMileagePrivate { get; set; }
        public string? AdditionalText { get; set; }
        public long? ParentId { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Ppminterval { get; set; }
        public long? PpmintervalTimeUnitId { get; set; }
        public DateTime? NextScheduleDate { get; set; }
        public decimal? NetBookValueWhenDisposed { get; set; }
        public DateTime? HoldUntilDate { get; set; }
        public string? HoldUntilPeriod { get; set; }
        public string? AnalysisCode1 { get; set; }
        public string? AnalysisCode2 { get; set; }
        public string? AnalysisCode3 { get; set; }
        public string? AnalysisCode4 { get; set; }
        public string? AnalysisCode5 { get; set; }
        public string? AnalysisCode6 { get; set; }
        public string? AnalysisCode7 { get; set; }
        public string? AnalysisCode8 { get; set; }
        public string? AnalysisCode9 { get; set; }
        public string? AnalysisCode10 { get; set; }
        public string? AnalysisCode11 { get; set; }
        public string? AnalysisCode12 { get; set; }
        public string? AnalysisCode13 { get; set; }
        public string? AnalysisCode14 { get; set; }
        public string? AnalysisCode15 { get; set; }
        public string? AnalysisCode16 { get; set; }
        public string? AnalysisCode17 { get; set; }
        public string? AnalysisCode18 { get; set; }
        public string? AnalysisCode19 { get; set; }
        public string? AnalysisCode20 { get; set; }
        public string? AnalysisCode21 { get; set; }
        public string? AnalysisCode22 { get; set; }
        public string? AnalysisCode23 { get; set; }
        public string? AnalysisCode24 { get; set; }
        public string? AnalysisCode25 { get; set; }
        public string? AnalysisCode26 { get; set; }
        public string? AnalysisCode27 { get; set; }
        public string? AnalysisCode28 { get; set; }
        public string? AnalysisCode29 { get; set; }
        public string? AnalysisCode30 { get; set; }
        public string? AnalysisCode31 { get; set; }
        public string? AnalysisCode32 { get; set; }
        public string? AnalysisCode33 { get; set; }
        public string? AnalysisCode34 { get; set; }
        public string? AnalysisCode35 { get; set; }
        public string? AnalysisCode36 { get; set; }
        public string? AnalysisCode37 { get; set; }
        public string? AnalysisCode38 { get; set; }
        public string? AnalysisCode39 { get; set; }
        public string? AnalysisCode40 { get; set; }
        public string? AnalysisCode41 { get; set; }
        public string? AnalysisCode42 { get; set; }
        public string? AnalysisCode43 { get; set; }
        public string? AnalysisCode44 { get; set; }
        public string? AnalysisCode45 { get; set; }
        public string? AnalysisCode46 { get; set; }
        public string? AnalysisCode47 { get; set; }
        public string? AnalysisCode48 { get; set; }
        public string? AnalysisCode49 { get; set; }
        public string? AnalysisCode50 { get; set; }
        public string? AnalysisCode51 { get; set; }
        public string? AnalysisCode52 { get; set; }
        public string? AnalysisCode53 { get; set; }
        public string? AnalysisCode54 { get; set; }
        public string? AnalysisCode55 { get; set; }
        public string? AnalysisCode56 { get; set; }
        public string? AnalysisCode57 { get; set; }
        public string? AnalysisCode58 { get; set; }
        public string? AnalysisCode59 { get; set; }
        public string? AnalysisCode60 { get; set; }
        public string? AnalysisCode61 { get; set; }
        public string? AnalysisCode62 { get; set; }
        public string? AnalysisCode63 { get; set; }
        public string? AnalysisCode64 { get; set; }
        public string? AnalysisCode65 { get; set; }
        public string? AnalysisCode66 { get; set; }
        public string? AnalysisCode67 { get; set; }
        public string? AnalysisCode68 { get; set; }
        public string? AnalysisCode69 { get; set; }
        public string? AnalysisCode70 { get; set; }
        public string? AnalysisCode71 { get; set; }
        public string? AnalysisCode72 { get; set; }
        public string? AnalysisCode73 { get; set; }
        public string? AnalysisCode74 { get; set; }
        public string? AnalysisCode75 { get; set; }
        public string? AnalysisCode76 { get; set; }
        public string? AnalysisCode77 { get; set; }
        public string? AnalysisCode78 { get; set; }
        public string? AnalysisCode79 { get; set; }
        public string? AnalysisCode80 { get; set; }
        public string? AnalysisCode81 { get; set; }
        public string? AnalysisCode82 { get; set; }
        public string? AnalysisCode83 { get; set; }
        public string? AnalysisCode84 { get; set; }
        public string? AnalysisCode85 { get; set; }
        public string? AnalysisCode86 { get; set; }
        public string? AnalysisCode87 { get; set; }
        public string? AnalysisCode88 { get; set; }
        public string? AnalysisCode89 { get; set; }
        public string? AnalysisCode90 { get; set; }
        public string? AnalysisCode91 { get; set; }
        public string? AnalysisCode92 { get; set; }
        public string? AnalysisCode93 { get; set; }
        public string? AnalysisCode94 { get; set; }
        public string? AnalysisCode95 { get; set; }
        public string? AnalysisCode96 { get; set; }
        public string? AnalysisCode97 { get; set; }
        public string? AnalysisCode98 { get; set; }
        public string? AnalysisCode99 { get; set; }
        public string? AnalysisCode100 { get; set; }
        public string? AnalysisCode101 { get; set; }
        public string? AnalysisCode102 { get; set; }
        public string? AnalysisCode103 { get; set; }
        public string? AnalysisCode104 { get; set; }
        public string? AnalysisCode105 { get; set; }
        public string? AnalysisCode106 { get; set; }
        public string? AnalysisCode107 { get; set; }
        public string? AnalysisCode108 { get; set; }
        public string? AnalysisCode109 { get; set; }
        public string? AnalysisCode110 { get; set; }
        public string? AnalysisCode111 { get; set; }
        public string? AnalysisCode112 { get; set; }
        public string? AnalysisCode113 { get; set; }
        public string? AnalysisCode114 { get; set; }
        public string? AnalysisCode115 { get; set; }
        public string? AnalysisCode116 { get; set; }
        public string? AnalysisCode117 { get; set; }
        public string? AnalysisCode118 { get; set; }
        public string? AnalysisCode119 { get; set; }
        public string? AnalysisCode120 { get; set; }
        public string? AnalysisCode121 { get; set; }
        public string? AnalysisCode122 { get; set; }
        public string? AnalysisCode123 { get; set; }
        public string? AnalysisCode124 { get; set; }
        public string? AnalysisCode125 { get; set; }
        public string? AnalysisCode126 { get; set; }
        public string? AnalysisCode127 { get; set; }
        public string? AnalysisCode128 { get; set; }
        public string? AnalysisCode129 { get; set; }
        public string? AnalysisCode130 { get; set; }
        public string? AnalysisCode131 { get; set; }
        public string? AnalysisCode132 { get; set; }
        public string? AnalysisCode133 { get; set; }
        public string? AnalysisCode134 { get; set; }
        public string? AnalysisCode135 { get; set; }
        public string? AnalysisCode136 { get; set; }
        public string? AnalysisCode137 { get; set; }
        public string? AnalysisCode138 { get; set; }
        public string? AnalysisCode139 { get; set; }
        public string? AnalysisCode140 { get; set; }
        public string? AnalysisCode141 { get; set; }
        public string? AnalysisCode142 { get; set; }
        public string? AnalysisCode143 { get; set; }
        public string? AnalysisCode144 { get; set; }
        public string? AnalysisCode145 { get; set; }
        public string? AnalysisCode146 { get; set; }
        public string? AnalysisCode147 { get; set; }
        public string? AnalysisCode148 { get; set; }
        public string? AnalysisCode149 { get; set; }
        public string? AnalysisCode150 { get; set; }
        public decimal? MonthlyDepValue { get; set; }
        public long? SiconHmfixedAssetHireStatusId { get; set; }
        public long? WarehouseId { get; set; }
        public long? BinItemId { get; set; }
        public DateTime? DateOfLastExamination { get; set; }
        public DateTime? LastReceiveDate { get; set; }
        public long? LastHireOrderId { get; set; }
        public bool? AssetReserved { get; set; }
        public bool? UseMeterReadings { get; set; }
        public decimal? MeterReadingValue { get; set; }
        public decimal? QuantityAvailableForHire { get; set; }
        public decimal? QuantityOnHire { get; set; }
        public decimal? QuantityAllocated { get; set; }
        public decimal? QuantityInInspection { get; set; }
        public long? LastSiconHmorderLineId { get; set; }
        public string? AssetReservedByUserId { get; set; }
        public DateTime? AssetReservedDateTime { get; set; }
        public DateTime? DateFirstAvailableForHire { get; set; }
        public long? SiconHmassetConditionId { get; set; }
        public decimal? RechargeSellingPrice { get; set; }
        public decimal? QuantityLost { get; set; }
    }
}
