using System;
using System.Collections.Generic;

namespace MinimalApiTest.Domain.SageModels
{
    public partial class SiconStockTraceableAttribute
    {
        public long SiconStockTraceableAttributeId { get; set; }
        public long? StockItemId { get; set; }
        public long? TraceableItemId { get; set; }
        public string? AttributeTitle1 { get; set; }
        public string? AttributeValue1 { get; set; }
        public string? AttributeTitle2 { get; set; }
        public string? AttributeValue2 { get; set; }
        public string? AttributeTitle3 { get; set; }
        public string? AttributeValue3 { get; set; }
        public string? AttributeTitle4 { get; set; }
        public string? AttributeValue4 { get; set; }
        public string? AttributeTitle5 { get; set; }
        public string? AttributeValue5 { get; set; }
        public string? AttributeTitle6 { get; set; }
        public string? AttributeValue6 { get; set; }
        public string? AttributeTitle7 { get; set; }
        public string? AttributeValue7 { get; set; }
        public string? AttributeTitle8 { get; set; }
        public string? AttributeValue8 { get; set; }
        public string? AttributeTitle9 { get; set; }
        public string? AttributeValue9 { get; set; }
        public string? AttributeTitle10 { get; set; }
        public string? AttributeValue10 { get; set; }
        public string? AttributeTitle11 { get; set; }
        public string? AttributeValue11 { get; set; }
        public string? AttributeTitle12 { get; set; }
        public string? AttributeValue12 { get; set; }
        public string? AttributeTitle13 { get; set; }
        public string? AttributeValue13 { get; set; }
        public string? AttributeTitle14 { get; set; }
        public string? AttributeValue14 { get; set; }
        public string? AttributeTitle15 { get; set; }
        public string? AttributeValue15 { get; set; }
        public string? AttributeTitle16 { get; set; }
        public string? AttributeValue16 { get; set; }
        public string? AttributeTitle17 { get; set; }
        public string? AttributeValue17 { get; set; }
        public string? AttributeTitle18 { get; set; }
        public string? AttributeValue18 { get; set; }
        public string? AttributeTitle19 { get; set; }
        public string? AttributeValue19 { get; set; }
        public string? AttributeTitle20 { get; set; }
        public string? AttributeValue20 { get; set; }
        public string? AttributeTitle21 { get; set; }
        public string? AttributeValue21 { get; set; }
        public string? AttributeTitle22 { get; set; }
        public string? AttributeValue22 { get; set; }
        public string? AttributeTitle23 { get; set; }
        public string? AttributeValue23 { get; set; }
        public string? AttributeTitle24 { get; set; }
        public string? AttributeValue24 { get; set; }
        public string? AttributeTitle25 { get; set; }
        public string? AttributeValue25 { get; set; }
        public string? AttributeTitle26 { get; set; }
        public string? AttributeValue26 { get; set; }
        public string? AttributeTitle27 { get; set; }
        public string? AttributeValue27 { get; set; }
        public string? AttributeTitle28 { get; set; }
        public string? AttributeValue28 { get; set; }
        public string? AttributeTitle29 { get; set; }
        public string? AttributeValue29 { get; set; }
        public string? AttributeTitle30 { get; set; }
        public string? AttributeValue30 { get; set; }
        public string? AttributeTitle31 { get; set; }
        public string? AttributeValue31 { get; set; }
        public string? AttributeTitle32 { get; set; }
        public string? AttributeValue32 { get; set; }
        public string? AttributeTitle33 { get; set; }
        public string? AttributeValue33 { get; set; }
        public string? AttributeTitle34 { get; set; }
        public string? AttributeValue34 { get; set; }
        public string? AttributeTitle35 { get; set; }
        public string? AttributeValue35 { get; set; }
        public string? AttributeTitle36 { get; set; }
        public string? AttributeValue36 { get; set; }
        public string? AttributeTitle37 { get; set; }
        public string? AttributeValue37 { get; set; }
        public string? AttributeTitle38 { get; set; }
        public string? AttributeValue38 { get; set; }
        public string? AttributeTitle39 { get; set; }
        public string? AttributeValue39 { get; set; }
        public string? AttributeTitle40 { get; set; }
        public string? AttributeValue40 { get; set; }
        public string? AttributeTitle41 { get; set; }
        public string? AttributeValue41 { get; set; }
        public string? AttributeTitle42 { get; set; }
        public string? AttributeValue42 { get; set; }
        public string? AttributeTitle43 { get; set; }
        public string? AttributeValue43 { get; set; }
        public string? AttributeTitle44 { get; set; }
        public string? AttributeValue44 { get; set; }
        public string? AttributeTitle45 { get; set; }
        public string? AttributeValue45 { get; set; }
        public string? AttributeTitle46 { get; set; }
        public string? AttributeValue46 { get; set; }
        public string? AttributeTitle47 { get; set; }
        public string? AttributeValue47 { get; set; }
        public string? AttributeTitle48 { get; set; }
        public string? AttributeValue48 { get; set; }
        public string? AttributeTitle49 { get; set; }
        public string? AttributeValue49 { get; set; }
        public string? AttributeTitle50 { get; set; }
        public string? AttributeValue50 { get; set; }
        public string? DeletedUserId { get; set; }
        public DateTime? DeletedDateTime { get; set; }
        public string? LastUpdatedByUserId { get; set; }
        public DateTime? LastUpdatedDateTime { get; set; }
    }
}
