using System;
using System.Collections.Generic;

namespace MinimalApiTest.Domain.SageModels
{
    public partial class SiconStockItemAnalysis
    {
        public long SiconStockItemAnalysisId { get; set; }
        public long? ItemId { get; set; }
        public string? AnalysisText1 { get; set; }
        public string? AnalysisText2 { get; set; }
        public string? AnalysisText3 { get; set; }
        public string? AnalysisText4 { get; set; }
        public string? AnalysisText5 { get; set; }
        public string? AnalysisText6 { get; set; }
        public string? AnalysisText7 { get; set; }
        public string? AnalysisText8 { get; set; }
        public string? AnalysisText9 { get; set; }
        public string? AnalysisText10 { get; set; }
        public string? AnalysisText11 { get; set; }
        public string? AnalysisText12 { get; set; }
        public string? AnalysisText13 { get; set; }
        public string? AnalysisText14 { get; set; }
        public string? AnalysisText15 { get; set; }
        public string? AnalysisText16 { get; set; }
        public string? AnalysisText17 { get; set; }
        public string? AnalysisText18 { get; set; }
        public string? AnalysisText19 { get; set; }
        public string? AnalysisText20 { get; set; }
        public string? AnalysisText21 { get; set; }
        public string? AnalysisText22 { get; set; }
        public string? AnalysisText23 { get; set; }
        public string? AnalysisText24 { get; set; }
        public string? AnalysisText25 { get; set; }
        public string? AnalysisText26 { get; set; }
        public string? AnalysisText27 { get; set; }
        public string? AnalysisText28 { get; set; }
        public string? AnalysisText29 { get; set; }
        public string? AnalysisText30 { get; set; }
        public string? AnalysisText31 { get; set; }
        public string? AnalysisText32 { get; set; }
        public string? AnalysisText33 { get; set; }
        public string? AnalysisText34 { get; set; }
        public string? AnalysisText35 { get; set; }
        public string? AnalysisText36 { get; set; }
        public string? AnalysisText37 { get; set; }
        public string? AnalysisText38 { get; set; }
        public string? AnalysisText39 { get; set; }
        public string? AnalysisText40 { get; set; }
        public string? AnalysisText41 { get; set; }
        public string? AnalysisText42 { get; set; }
        public string? AnalysisText43 { get; set; }
        public string? AnalysisText44 { get; set; }
        public string? AnalysisText45 { get; set; }
        public string? AnalysisText46 { get; set; }
        public string? AnalysisText47 { get; set; }
        public string? AnalysisText48 { get; set; }
        public string? AnalysisText49 { get; set; }
        public string? AnalysisText50 { get; set; }
        public string? AnalysisText51 { get; set; }
        public string? AnalysisText52 { get; set; }
        public string? AnalysisText53 { get; set; }
        public string? AnalysisText54 { get; set; }
        public string? AnalysisText55 { get; set; }
        public string? AnalysisText56 { get; set; }
        public string? AnalysisText57 { get; set; }
        public string? AnalysisText58 { get; set; }
        public string? AnalysisText59 { get; set; }
        public string? AnalysisText60 { get; set; }
        public string? AnalysisText61 { get; set; }
        public string? AnalysisText62 { get; set; }
        public string? AnalysisText63 { get; set; }
        public string? AnalysisText64 { get; set; }
        public string? AnalysisText65 { get; set; }
        public string? AnalysisText66 { get; set; }
        public string? AnalysisText67 { get; set; }
        public string? AnalysisText68 { get; set; }
        public string? AnalysisText69 { get; set; }
        public string? AnalysisText70 { get; set; }
        public string? AnalysisText71 { get; set; }
        public string? AnalysisText72 { get; set; }
        public string? AnalysisText73 { get; set; }
        public string? AnalysisText74 { get; set; }
        public string? AnalysisText75 { get; set; }
        public string? AnalysisText76 { get; set; }
        public string? AnalysisText77 { get; set; }
        public string? AnalysisText78 { get; set; }
        public string? AnalysisText79 { get; set; }
        public string? AnalysisText80 { get; set; }
        public string? AnalysisText81 { get; set; }
        public string? AnalysisText82 { get; set; }
        public string? AnalysisText83 { get; set; }
        public string? AnalysisText84 { get; set; }
        public string? AnalysisText85 { get; set; }
        public string? AnalysisText86 { get; set; }
        public string? AnalysisText87 { get; set; }
        public string? AnalysisText88 { get; set; }
        public string? AnalysisText89 { get; set; }
        public string? AnalysisText90 { get; set; }
        public string? AnalysisText91 { get; set; }
        public string? AnalysisText92 { get; set; }
        public string? AnalysisText93 { get; set; }
        public string? AnalysisText94 { get; set; }
        public string? AnalysisText95 { get; set; }
        public string? AnalysisText96 { get; set; }
        public string? AnalysisText97 { get; set; }
        public string? AnalysisText98 { get; set; }
        public string? AnalysisText99 { get; set; }
        public string? AnalysisText100 { get; set; }
        public string? AnalysisText101 { get; set; }
        public string? AnalysisText102 { get; set; }
        public string? AnalysisText103 { get; set; }
        public string? AnalysisText104 { get; set; }
        public string? AnalysisText105 { get; set; }
        public string? AnalysisText106 { get; set; }
        public string? AnalysisText107 { get; set; }
        public string? AnalysisText108 { get; set; }
        public string? AnalysisText109 { get; set; }
        public string? AnalysisText110 { get; set; }
        public string? AnalysisText111 { get; set; }
        public string? AnalysisText112 { get; set; }
        public string? AnalysisText113 { get; set; }
        public string? AnalysisText114 { get; set; }
        public string? AnalysisText115 { get; set; }
        public string? AnalysisText116 { get; set; }
        public string? AnalysisText117 { get; set; }
        public string? AnalysisText118 { get; set; }
        public string? AnalysisText119 { get; set; }
        public string? AnalysisText120 { get; set; }
        public string? AnalysisText121 { get; set; }
        public string? AnalysisText122 { get; set; }
        public string? AnalysisText123 { get; set; }
        public string? AnalysisText124 { get; set; }
        public string? AnalysisText125 { get; set; }
        public string? AnalysisText126 { get; set; }
        public string? AnalysisText127 { get; set; }
        public string? AnalysisText128 { get; set; }
        public string? AnalysisText129 { get; set; }
        public string? AnalysisText130 { get; set; }
        public string? AnalysisText131 { get; set; }
        public string? AnalysisText132 { get; set; }
        public string? AnalysisText133 { get; set; }
        public string? AnalysisText134 { get; set; }
        public string? AnalysisText135 { get; set; }
        public string? AnalysisText136 { get; set; }
        public string? AnalysisText137 { get; set; }
        public string? AnalysisText138 { get; set; }
        public string? AnalysisText139 { get; set; }
        public string? AnalysisText140 { get; set; }
        public string? AnalysisText141 { get; set; }
        public string? AnalysisText142 { get; set; }
        public string? AnalysisText143 { get; set; }
        public string? AnalysisText144 { get; set; }
        public string? AnalysisText145 { get; set; }
        public string? AnalysisText146 { get; set; }
        public string? AnalysisText147 { get; set; }
        public string? AnalysisText148 { get; set; }
        public string? AnalysisText149 { get; set; }
        public string? AnalysisText150 { get; set; }
        public decimal AnalysisNumber1 { get; set; }
        public decimal AnalysisNumber2 { get; set; }
        public decimal AnalysisNumber3 { get; set; }
        public decimal AnalysisNumber4 { get; set; }
        public decimal AnalysisNumber5 { get; set; }
        public string? LastUpdatedByUserId { get; set; }
        public DateTime? LastUpdatedDateTime { get; set; }
    }
}
