using System;
using System.Collections.Generic;

namespace MinimalApiTest.Domain.SageModels
{
    public partial class SiconContractLine
    {
        public long SiconContractLineId { get; set; }
        public long SiconContractId { get; set; }
        public DateTime? OrderDate { get; set; }
        public string? WhoSoldText { get; set; }
        public string CustomerContact { get; set; } = null!;
        public DateTime? AnnualReviewDate { get; set; }
        public string ContractTypeText { get; set; } = null!;
        public string VisitFrequencyText { get; set; } = null!;
        public string PaymentTypeText { get; set; } = null!;
        public DateTime? RemovedDate { get; set; }
        public string SpareText1 { get; set; } = null!;
        public string SpareText2 { get; set; } = null!;
        public string SpareText3 { get; set; } = null!;
        public string SpareText4 { get; set; } = null!;
        public string SpareText5 { get; set; } = null!;
        public string SpareText6 { get; set; } = null!;
        public string SpareText7 { get; set; } = null!;
        public decimal SpareNumber1 { get; set; }
        public decimal SpareNumber2 { get; set; }
        public decimal SpareNumber3 { get; set; }
        public decimal SpareNumber4 { get; set; }
        public decimal SpareNumber5 { get; set; }
        public decimal SpareNumber6 { get; set; }
        public decimal SpareNumber7 { get; set; }
        public DateTime? SpareDateTime1 { get; set; }
        public DateTime? SpareDateTime2 { get; set; }
        public DateTime? SpareDateTime3 { get; set; }
        public DateTime? SpareDateTime4 { get; set; }
        public DateTime? SpareDateTime5 { get; set; }
        public DateTime? SpareDateTime6 { get; set; }
        public DateTime? SpareDateTime7 { get; set; }
        public string DeletedByUserId { get; set; } = null!;
        public DateTime? DeletedDateTime { get; set; }
        public string LastUpdatedByUserId { get; set; } = null!;
        public DateTime? LastUpdatedDateTime { get; set; }
        public DateTime? BillCoverFromDate { get; set; }
        public DateTime? BillCoverToDate { get; set; }
        public bool? PartsIncludedOnContract { get; set; }
        public bool? LabourIncludedOnContract { get; set; }
        public long? SiconContractCoverTypeId { get; set; }
        public long? NlrevenueNominalCodeId { get; set; }
        public long? NldeferredRevenueNominalCodeId { get; set; }
        public long? NlbsdeferredCostNominalCodeId { get; set; }
        public long? NlplcostNominalCodeId { get; set; }
        public long? ItemId { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? UnitPrice { get; set; }
        public string? Description { get; set; }
        public bool? RenewAutomatically { get; set; }
        public DateTime? NextInvoiceDate { get; set; }
        public short? FrequencyValue { get; set; }
        public long? FrequencyTimeUnitId { get; set; }
        public string? PaidStatus { get; set; }
        public short? GracePeriodValue { get; set; }
        public long? GracePeriodTimeUnitId { get; set; }
        public long? SopcustDeliveryAddressId { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public bool? ContractLineDeleted { get; set; }
        public decimal? RenewalUnitPrice { get; set; }
        public decimal? RenewalQuantity { get; set; }
        public decimal? AmendedQuantity { get; set; }
        public decimal? AmendedUnitPrice { get; set; }
        public long? WarehouseId { get; set; }
        public bool? IsNew { get; set; }
        public short? InvoiceBeforeContractStart { get; set; }
        public short? RenewalNotice { get; set; }
        public decimal? AmendedQuantityGenerated { get; set; }
        public decimal? UnitCost { get; set; }
        public bool? ProRata { get; set; }
        public DateTime? StartDate { get; set; }
        public bool? RenewConfirmed { get; set; }
        public string? RenewedBy { get; set; }
        public DateTime? RenewDate { get; set; }
        public short? RenewalDuration { get; set; }
        public short? RenewalInvoiceFrequencyValue { get; set; }
        public long? ReasonForLeavingId { get; set; }
        public bool? ExtendedTerm { get; set; }
        public string? AnalysisCode1 { get; set; }
        public string? AnalysisCode2 { get; set; }
        public string? AnalysisCode3 { get; set; }
        public string? AnalysisCode4 { get; set; }
        public string? AnalysisCode5 { get; set; }
        public string? AnalysisCode6 { get; set; }
        public string? AnalysisCode7 { get; set; }
        public string? AnalysisCode8 { get; set; }
        public string? AnalysisCode9 { get; set; }
        public string? AnalysisCode10 { get; set; }
        public string? AnalysisCode11 { get; set; }
        public string? AnalysisCode12 { get; set; }
        public string? AnalysisCode13 { get; set; }
        public string? AnalysisCode14 { get; set; }
        public string? AnalysisCode15 { get; set; }
        public string? AnalysisCode16 { get; set; }
        public string? AnalysisCode17 { get; set; }
        public string? AnalysisCode18 { get; set; }
        public string? AnalysisCode19 { get; set; }
        public string? AnalysisCode20 { get; set; }
        public string? ClanalysisCode1 { get; set; }
        public string? ClanalysisCode2 { get; set; }
        public string? ClanalysisCode3 { get; set; }
        public string? ClanalysisCode4 { get; set; }
        public string? ClanalysisCode5 { get; set; }
        public string? ClanalysisCode6 { get; set; }
        public string? ClanalysisCode7 { get; set; }
        public string? ClanalysisCode8 { get; set; }
        public string? ClanalysisCode9 { get; set; }
        public string? ClanalysisCode10 { get; set; }
        public string? ClanalysisCode11 { get; set; }
        public string? ClanalysisCode12 { get; set; }
        public string? ClanalysisCode13 { get; set; }
        public string? ClanalysisCode14 { get; set; }
        public string? ClanalysisCode15 { get; set; }
        public string? ClanalysisCode16 { get; set; }
        public string? ClanalysisCode17 { get; set; }
        public string? ClanalysisCode18 { get; set; }
        public string? ClanalysisCode19 { get; set; }
        public string? ClanalysisCode20 { get; set; }
        public string? ClanalysisCode21 { get; set; }
        public string? ClanalysisCode22 { get; set; }
        public string? ClanalysisCode23 { get; set; }
        public string? ClanalysisCode24 { get; set; }
        public string? ClanalysisCode25 { get; set; }
        public string? ClanalysisCode26 { get; set; }
        public string? ClanalysisCode27 { get; set; }
        public string? ClanalysisCode28 { get; set; }
        public string? ClanalysisCode29 { get; set; }
        public string? ClanalysisCode30 { get; set; }
        public string? ClanalysisCode31 { get; set; }
        public string? ClanalysisCode32 { get; set; }
        public string? ClanalysisCode33 { get; set; }
        public string? ClanalysisCode34 { get; set; }
        public string? ClanalysisCode35 { get; set; }
        public string? ClanalysisCode36 { get; set; }
        public string? ClanalysisCode37 { get; set; }
        public string? ClanalysisCode38 { get; set; }
        public string? ClanalysisCode39 { get; set; }
        public string? ClanalysisCode40 { get; set; }
        public string? ClanalysisCode41 { get; set; }
        public string? ClanalysisCode42 { get; set; }
        public string? ClanalysisCode43 { get; set; }
        public string? ClanalysisCode44 { get; set; }
        public string? ClanalysisCode45 { get; set; }
        public string? ClanalysisCode46 { get; set; }
        public string? ClanalysisCode47 { get; set; }
        public string? ClanalysisCode48 { get; set; }
        public string? ClanalysisCode49 { get; set; }
        public string? ClanalysisCode50 { get; set; }
        public string? ClanalysisCode51 { get; set; }
        public string? ClanalysisCode52 { get; set; }
        public string? ClanalysisCode53 { get; set; }
        public string? ClanalysisCode54 { get; set; }
        public string? ClanalysisCode55 { get; set; }
        public string? ClanalysisCode56 { get; set; }
        public string? ClanalysisCode57 { get; set; }
        public string? ClanalysisCode58 { get; set; }
        public string? ClanalysisCode59 { get; set; }
        public string? ClanalysisCode60 { get; set; }
        public string? ClanalysisCode61 { get; set; }
        public string? ClanalysisCode62 { get; set; }
        public string? ClanalysisCode63 { get; set; }
        public string? ClanalysisCode64 { get; set; }
        public string? ClanalysisCode65 { get; set; }
        public string? ClanalysisCode66 { get; set; }
        public string? ClanalysisCode67 { get; set; }
        public string? ClanalysisCode68 { get; set; }
        public string? ClanalysisCode69 { get; set; }
        public string? ClanalysisCode70 { get; set; }
        public string? ClanalysisCode71 { get; set; }
        public string? ClanalysisCode72 { get; set; }
        public string? ClanalysisCode73 { get; set; }
        public string? ClanalysisCode74 { get; set; }
        public string? ClanalysisCode75 { get; set; }
        public string? ClanalysisCode76 { get; set; }
        public string? ClanalysisCode77 { get; set; }
        public string? ClanalysisCode78 { get; set; }
        public string? ClanalysisCode79 { get; set; }
        public string? ClanalysisCode80 { get; set; }
        public string? ClanalysisCode81 { get; set; }
        public string? ClanalysisCode82 { get; set; }
        public string? ClanalysisCode83 { get; set; }
        public string? ClanalysisCode84 { get; set; }
        public string? ClanalysisCode85 { get; set; }
        public string? ClanalysisCode86 { get; set; }
        public string? ClanalysisCode87 { get; set; }
        public string? ClanalysisCode88 { get; set; }
        public string? ClanalysisCode89 { get; set; }
        public string? ClanalysisCode90 { get; set; }
        public string? ClanalysisCode91 { get; set; }
        public string? ClanalysisCode92 { get; set; }
        public string? ClanalysisCode93 { get; set; }
        public string? ClanalysisCode94 { get; set; }
        public string? ClanalysisCode95 { get; set; }
        public string? ClanalysisCode96 { get; set; }
        public string? ClanalysisCode97 { get; set; }
        public string? ClanalysisCode98 { get; set; }
        public string? ClanalysisCode99 { get; set; }
        public string? ClanalysisCode100 { get; set; }
        public string? ClanalysisCode101 { get; set; }
        public string? ClanalysisCode102 { get; set; }
        public string? ClanalysisCode103 { get; set; }
        public string? ClanalysisCode104 { get; set; }
        public string? ClanalysisCode105 { get; set; }
        public string? ClanalysisCode106 { get; set; }
        public string? ClanalysisCode107 { get; set; }
        public string? ClanalysisCode108 { get; set; }
        public string? ClanalysisCode109 { get; set; }
        public string? ClanalysisCode110 { get; set; }
        public string? ClanalysisCode111 { get; set; }
        public string? ClanalysisCode112 { get; set; }
        public string? ClanalysisCode113 { get; set; }
        public string? ClanalysisCode114 { get; set; }
        public string? ClanalysisCode115 { get; set; }
        public string? ClanalysisCode116 { get; set; }
        public string? ClanalysisCode117 { get; set; }
        public string? ClanalysisCode118 { get; set; }
        public string? ClanalysisCode119 { get; set; }
        public string? ClanalysisCode120 { get; set; }
        public string? ClanalysisCode121 { get; set; }
        public string? ClanalysisCode122 { get; set; }
        public string? ClanalysisCode123 { get; set; }
        public string? ClanalysisCode124 { get; set; }
        public string? ClanalysisCode125 { get; set; }
        public string? ClanalysisCode126 { get; set; }
        public string? ClanalysisCode127 { get; set; }
        public string? ClanalysisCode128 { get; set; }
        public string? ClanalysisCode129 { get; set; }
        public string? ClanalysisCode130 { get; set; }
        public string? ClanalysisCode131 { get; set; }
        public string? ClanalysisCode132 { get; set; }
        public string? ClanalysisCode133 { get; set; }
        public string? ClanalysisCode134 { get; set; }
        public string? ClanalysisCode135 { get; set; }
        public string? ClanalysisCode136 { get; set; }
        public string? ClanalysisCode137 { get; set; }
        public string? ClanalysisCode138 { get; set; }
        public string? ClanalysisCode139 { get; set; }
        public string? ClanalysisCode140 { get; set; }
        public string? ClanalysisCode141 { get; set; }
        public string? ClanalysisCode142 { get; set; }
        public string? ClanalysisCode143 { get; set; }
        public string? ClanalysisCode144 { get; set; }
        public string? ClanalysisCode145 { get; set; }
        public string? ClanalysisCode146 { get; set; }
        public string? ClanalysisCode147 { get; set; }
        public string? ClanalysisCode148 { get; set; }
        public string? ClanalysisCode149 { get; set; }
        public string? ClanalysisCode150 { get; set; }
        public bool? ConfirmAmend { get; set; }
        public int? NumberOfInvoicesRemaining { get; set; }
        public DateTime? AmendedContractEndDate { get; set; }
        public DateTime? AmendedTerminationDate { get; set; }
        public short? ContractDuration { get; set; }
        public short? BillCoverDuration { get; set; }
        public bool? RenewalPriceUpdated { get; set; }
        public bool? ThirtyDayReminderPrinted { get; set; }
        public bool? SixtyDayReminderPrinted { get; set; }
        public bool? Expired { get; set; }
        public string? ComplimentaryCode { get; set; }
        public DateTime? CancellationDate { get; set; }
        public int? LineNumber { get; set; }
        public bool? Complimentary { get; set; }
        public bool? Suspended { get; set; }
        public bool? Cancelled { get; set; }
        public decimal? UnitBillCoverPriceIncDisc { get; set; }
        public DateTime? ProRataDate { get; set; }
        public long? SiJcJobId { get; set; }
        public long? SiJcChdId { get; set; }
        public short? InitialContractDuration { get; set; }
        public short? ExtendedContractDuration { get; set; }
        public bool? IsLocked { get; set; }
        public decimal? LastUnitPriceIncDiscPaid { get; set; }
        public decimal? DiscountValue { get; set; }
        public decimal? DiscountPercent { get; set; }
        public decimal? DiscountProRataValue { get; set; }
        public decimal? RenewalDiscountValue { get; set; }
        public decimal? RenewalDiscountPercent { get; set; }
        public bool? TravelIncludedOnContract { get; set; }
        public decimal TravelHoursIncludedOnContract { get; set; }
        public decimal LabourDiscountPercOnContract { get; set; }
        public decimal LabourHoursIncludedOnContract { get; set; }
        public decimal PartsDiscountPercentOnContract { get; set; }
        public bool? IsRollingContract { get; set; }
        public string? InternalDescription { get; set; }
        public decimal? NumberOfSalesOrdersGenerated { get; set; }
        public bool? CurrentInvoiceAlreadyGenerated { get; set; }
        public int? BillMonthInAdvanceArrearsQty { get; set; }
        public bool? BillInArrears { get; set; }
        public bool? IsNewRenewal { get; set; }
        public long? TimeRounding { get; set; }
        public decimal? CalloutCharge { get; set; }
        public decimal? MaxSellingValue { get; set; }
        public long? SiSmpriorityId { get; set; }
        public decimal? RenewalUnitCost { get; set; }
        public DateTime? NextDueDate { get; set; }
        public bool? ReadyToInvoice { get; set; }
        public string? SuspendedReason { get; set; }
        public long? PlsupplierAccountId { get; set; }
        public decimal? SupplierUnitPrice { get; set; }
        public string? SupplierDescription { get; set; }
        public decimal? SubsequentCalloutCharge { get; set; }
        public DateTime? AmendmentProRataDate { get; set; }
        public bool? AmendmentProRata { get; set; }
        public decimal? AmendmentOneOffUnitPrice { get; set; }
        public DateTime? AmendmentOneOffFromDate { get; set; }
        public short? AmendmentOneOffDuration { get; set; }
        public bool? DirectDebitCollection { get; set; }
        public long? AmendmentTypeId { get; set; }
        public DateTime? ContractEndDateIncludingPog { get; set; }
        public long? BranchId { get; set; }
        public bool? PendingLine { get; set; }
        public short? PreferredDayOfMonth { get; set; }
        public bool? PriceConfirmed { get; set; }
        public bool? RenewalIncreaseByPercent { get; set; }
        public decimal? RenewalIncreaseByPercentValue { get; set; }
        public DateTime? NextDateOfVariableBilling { get; set; }
        public bool? CustomFrequency { get; set; }
        public string? CustomersPurchaseOrderNumber { get; set; }
        public string? AmendmentOneOffDescription { get; set; }
        public DateTime? LastDateOfVariableBilling { get; set; }
        public long? PriceFrequencyTimeUnitId { get; set; }
        public bool? Trial { get; set; }
        public long? RenewalFrequencyTimeUnitId { get; set; }
        public long? RenewalPriceFreqTimeUnitId { get; set; }
        public long? AssociatedSlcustAccId { get; set; }
        public long? SiconCrmpersonId { get; set; }
        public long? SiconCrmcompanyId { get; set; }
        public long? AssociatedSiconCrmcompanyId { get; set; }
        public decimal? FirstHourRate { get; set; }
        public decimal? SubsequentHourRate { get; set; }
        public bool? OverrideLabourRates { get; set; }
        public decimal? MaxTravelChargeHours { get; set; }
        public bool? HalfHourPeriodForLabOverride { get; set; }
        public long? WorkPatternOverrideId { get; set; }
        public decimal? MileageChargeRate { get; set; }
        public decimal? FixedPriceValue { get; set; }
        public long? FixedPriceStockItemId { get; set; }
        public bool? UseFixedPrice { get; set; }
        public bool? ExpensesIncluded { get; set; }
        public decimal? ExpenseMarkup { get; set; }
    }
}
