using System;
using System.Collections.Generic;

namespace MinimalApiTest.Domain.SageModels
{
    public partial class Sijcemp
    {
        public long SiJcEmpId { get; set; }
        public bool? IsEmployee { get; set; }
        public bool? IsJobManager { get; set; }
        public string? FirstName { get; set; }
        public string? Surname { get; set; }
        public long? EmployeeNumber { get; set; }
        public string? PayrollReference { get; set; }
        public string? SpareText1 { get; set; }
        public string? SpareText2 { get; set; }
        public string? SpareText3 { get; set; }
        public string? SpareText4 { get; set; }
        public string? SpareText5 { get; set; }
        public decimal? SpareNumber1 { get; set; }
        public decimal? SpareNumber2 { get; set; }
        public decimal? SpareNumber3 { get; set; }
        public decimal? SpareNumber4 { get; set; }
        public decimal? SpareNumber5 { get; set; }
        public decimal? SpareNumber6 { get; set; }
        public decimal? SpareNumber7 { get; set; }
        public decimal? SpareNumber8 { get; set; }
        public decimal? SpareNumber9 { get; set; }
        public decimal? SpareNumber10 { get; set; }
        public long? DefaultSiJcChdId { get; set; }
        public string? Email { get; set; }
        public long? SiJcRoleId { get; set; }
        public string? PostCodeArea { get; set; }
        public bool? SubContractor { get; set; }
        public long? PlsupplierAccountId { get; set; }
        public long? NextInvNo { get; set; }
        public long? CostRateNominalCodeId { get; set; }
        public long? ChargeRateNominalCodeId { get; set; }
        public long? WarehouseId { get; set; }
        public string? DiaryColour { get; set; }
        public string? PayTypeCode { get; set; }
        public bool? FormerEmployee { get; set; }
        public string? Deleted { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string? DeletedBy { get; set; }
        public string? UpdatedUser { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public long? SiJcWorkPatternId { get; set; }
        public long? SiJcWorkPatternCostingId { get; set; }
        public string? SageUserId { get; set; }
        public bool? IsTeamLeader { get; set; }
        public DateTime? ContractExpiryDate { get; set; }
        public string? TelephoneNumber { get; set; }
        public string? MobileNumber { get; set; }
        public string? AddressLine1 { get; set; }
        public string? AddressLine2 { get; set; }
        public string? AddressLine3 { get; set; }
        public string? AddressLine4 { get; set; }
        public string? AddressCity { get; set; }
        public string? AddressPostCode { get; set; }
        public string? BillingAlias { get; set; }
        public decimal? LastLatitude { get; set; }
        public decimal? LastLongitude { get; set; }
        public DateTime? LastLocationDate { get; set; }
        public long? Pin { get; set; }
        public bool? ShopFloorAppLicensed { get; set; }
        public bool? BarcodingAppLicensed { get; set; }
        public bool? Hidden { get; set; }
        public DateTime? StartDate { get; set; }
        public long? SyscountryCodeId { get; set; }
        public bool? IsDormant { get; set; }
        public long? LinkedSiconEmployeeId { get; set; }
        public long? LinkedSiconJobId { get; set; }
        public bool? IsPlantWrttenOff { get; set; }
        public DateTime? PlantExpectedReturnDate { get; set; }
        public DateTime? LastCalibrationDate { get; set; }
        public DateTime? NextCalibrationDate { get; set; }
        public DateTime? LastServiceDate { get; set; }
        public DateTime? NextServiceDate { get; set; }
        public decimal? AddressLatitude { get; set; }
        public decimal? AddressLongitude { get; set; }
        public string? SerialNumber { get; set; }
        public string? Ninumber { get; set; }
        public int? PlantType { get; set; }
        public string? PlantStatus { get; set; }
        public DateTime? PlantLastActivityDate { get; set; }
        public long? LinkedSiconPhaseId { get; set; }
        public long? LinkedSiconStageId { get; set; }
        public long? LinkedSiconActivityId { get; set; }
        public string? Username { get; set; }
        public string? PasswordHash { get; set; }
        public long? SiconCrmterritoryId { get; set; }
        public DateTime? PlantPurchasedDate { get; set; }
        public decimal? PlantPurchasedPrice { get; set; }
        public decimal? Rate1 { get; set; }
        public decimal? Rate2 { get; set; }
        public decimal? Rate3 { get; set; }
        public decimal? Rate4 { get; set; }
        public decimal? Rate5 { get; set; }
        public decimal? Rate6 { get; set; }
        public decimal? Rate7 { get; set; }
        public decimal? Rate8 { get; set; }
        public decimal? Rate9 { get; set; }
        public decimal? Rate10 { get; set; }
        public decimal? Rate11 { get; set; }
        public decimal? Rate12 { get; set; }
        public decimal? Rate13 { get; set; }
        public decimal? Rate14 { get; set; }
        public decimal? Rate15 { get; set; }
        public decimal? Rate16 { get; set; }
        public decimal? Rate17 { get; set; }
        public decimal? Rate18 { get; set; }
        public decimal? Rate19 { get; set; }
        public decimal? Rate20 { get; set; }
        public decimal? Rate21 { get; set; }
        public decimal? Rate22 { get; set; }
        public decimal? Rate23 { get; set; }
        public decimal? Rate24 { get; set; }
        public decimal? Rate25 { get; set; }
        public decimal? Rate26 { get; set; }
        public decimal? Rate27 { get; set; }
        public decimal? Rate28 { get; set; }
        public decimal? Rate29 { get; set; }
        public decimal? Rate30 { get; set; }
        public decimal? Rate31 { get; set; }
        public decimal? Rate32 { get; set; }
        public decimal? Rate33 { get; set; }
        public decimal? Rate34 { get; set; }
        public decimal? Rate35 { get; set; }
        public decimal? Rate36 { get; set; }
        public decimal? Rate37 { get; set; }
        public decimal? Rate38 { get; set; }
        public decimal? Rate39 { get; set; }
        public decimal? Rate40 { get; set; }
        public decimal? Rate41 { get; set; }
        public decimal? Rate42 { get; set; }
        public decimal? Rate43 { get; set; }
        public decimal? Rate44 { get; set; }
        public decimal? Rate45 { get; set; }
        public decimal? Rate46 { get; set; }
        public decimal? Rate47 { get; set; }
        public decimal? Rate48 { get; set; }
        public decimal? Rate49 { get; set; }
        public decimal? Rate50 { get; set; }
        public decimal? Rate51 { get; set; }
        public decimal? Rate52 { get; set; }
        public decimal? Rate53 { get; set; }
        public decimal? Rate54 { get; set; }
        public decimal? Rate55 { get; set; }
        public decimal? Rate56 { get; set; }
        public decimal? Rate57 { get; set; }
        public decimal? Rate58 { get; set; }
        public decimal? Rate59 { get; set; }
        public decimal? Rate60 { get; set; }
        public decimal? Rate61 { get; set; }
        public decimal? Rate62 { get; set; }
        public decimal? Rate63 { get; set; }
        public decimal? Rate64 { get; set; }
        public decimal? Rate65 { get; set; }
        public decimal? Rate66 { get; set; }
        public decimal? Rate67 { get; set; }
        public decimal? Rate68 { get; set; }
        public decimal? Rate69 { get; set; }
        public decimal? Rate70 { get; set; }
        public decimal? Rate71 { get; set; }
        public decimal? Rate72 { get; set; }
        public decimal? Rate73 { get; set; }
        public decimal? Rate74 { get; set; }
        public decimal? Rate75 { get; set; }
        public decimal? Rate76 { get; set; }
        public decimal? Rate77 { get; set; }
        public decimal? Rate78 { get; set; }
        public decimal? Rate79 { get; set; }
        public decimal? Rate80 { get; set; }
        public decimal? Rate81 { get; set; }
        public decimal? Rate82 { get; set; }
        public decimal? Rate83 { get; set; }
        public decimal? Rate84 { get; set; }
        public decimal? Rate85 { get; set; }
        public decimal? Rate86 { get; set; }
        public decimal? Rate87 { get; set; }
        public decimal? Rate88 { get; set; }
        public decimal? Rate89 { get; set; }
        public decimal? Rate90 { get; set; }
        public decimal? Rate91 { get; set; }
        public decimal? Rate92 { get; set; }
        public decimal? Rate93 { get; set; }
        public decimal? Rate94 { get; set; }
        public decimal? Rate95 { get; set; }
        public decimal? Rate96 { get; set; }
        public decimal? Rate97 { get; set; }
        public decimal? Rate98 { get; set; }
        public decimal? Rate99 { get; set; }
        public decimal? Rate100 { get; set; }
        public decimal? PayRate1 { get; set; }
        public decimal? PayRate2 { get; set; }
        public decimal? PayRate3 { get; set; }
        public decimal? PayRate4 { get; set; }
        public decimal? PayRate5 { get; set; }
        public decimal? PayRate6 { get; set; }
        public decimal? PayRate7 { get; set; }
        public decimal? PayRate8 { get; set; }
        public decimal? PayRate9 { get; set; }
        public decimal? PayRate10 { get; set; }
        public decimal? PayRate11 { get; set; }
        public decimal? PayRate12 { get; set; }
        public decimal? PayRate13 { get; set; }
        public decimal? PayRate14 { get; set; }
        public decimal? PayRate15 { get; set; }
        public decimal? PayRate16 { get; set; }
        public decimal? PayRate17 { get; set; }
        public decimal? PayRate18 { get; set; }
        public decimal? PayRate19 { get; set; }
        public decimal? PayRate20 { get; set; }
        public decimal? PayRate21 { get; set; }
        public decimal? PayRate22 { get; set; }
        public decimal? PayRate23 { get; set; }
        public decimal? PayRate24 { get; set; }
        public decimal? PayRate25 { get; set; }
        public decimal? PayRate26 { get; set; }
        public decimal? PayRate27 { get; set; }
        public decimal? PayRate28 { get; set; }
        public decimal? PayRate29 { get; set; }
        public decimal? PayRate30 { get; set; }
        public decimal? PayRate31 { get; set; }
        public decimal? PayRate32 { get; set; }
        public decimal? PayRate33 { get; set; }
        public decimal? PayRate34 { get; set; }
        public decimal? PayRate35 { get; set; }
        public decimal? PayRate36 { get; set; }
        public decimal? PayRate37 { get; set; }
        public decimal? PayRate38 { get; set; }
        public decimal? PayRate39 { get; set; }
        public decimal? PayRate40 { get; set; }
        public decimal? PayRate41 { get; set; }
        public decimal? PayRate42 { get; set; }
        public decimal? PayRate43 { get; set; }
        public decimal? PayRate44 { get; set; }
        public decimal? PayRate45 { get; set; }
        public decimal? PayRate46 { get; set; }
        public decimal? PayRate47 { get; set; }
        public decimal? PayRate48 { get; set; }
        public decimal? PayRate49 { get; set; }
        public decimal? PayRate50 { get; set; }
        public decimal? PayRate51 { get; set; }
        public decimal? PayRate52 { get; set; }
        public decimal? PayRate53 { get; set; }
        public decimal? PayRate54 { get; set; }
        public decimal? PayRate55 { get; set; }
        public decimal? PayRate56 { get; set; }
        public decimal? PayRate57 { get; set; }
        public decimal? PayRate58 { get; set; }
        public decimal? PayRate59 { get; set; }
        public decimal? PayRate60 { get; set; }
        public decimal? PayRate61 { get; set; }
        public decimal? PayRate62 { get; set; }
        public decimal? PayRate63 { get; set; }
        public decimal? PayRate64 { get; set; }
        public decimal? PayRate65 { get; set; }
        public decimal? PayRate66 { get; set; }
        public decimal? PayRate67 { get; set; }
        public decimal? PayRate68 { get; set; }
        public decimal? PayRate69 { get; set; }
        public decimal? PayRate70 { get; set; }
        public decimal? PayRate71 { get; set; }
        public decimal? PayRate72 { get; set; }
        public decimal? PayRate73 { get; set; }
        public decimal? PayRate74 { get; set; }
        public decimal? PayRate75 { get; set; }
        public decimal? PayRate76 { get; set; }
        public decimal? PayRate77 { get; set; }
        public decimal? PayRate78 { get; set; }
        public decimal? PayRate79 { get; set; }
        public decimal? PayRate80 { get; set; }
        public decimal? PayRate81 { get; set; }
        public decimal? PayRate82 { get; set; }
        public decimal? PayRate83 { get; set; }
        public decimal? PayRate84 { get; set; }
        public decimal? PayRate85 { get; set; }
        public decimal? PayRate86 { get; set; }
        public decimal? PayRate87 { get; set; }
        public decimal? PayRate88 { get; set; }
        public decimal? PayRate89 { get; set; }
        public decimal? PayRate90 { get; set; }
        public decimal? PayRate91 { get; set; }
        public decimal? PayRate92 { get; set; }
        public decimal? PayRate93 { get; set; }
        public decimal? PayRate94 { get; set; }
        public decimal? PayRate95 { get; set; }
        public decimal? PayRate96 { get; set; }
        public decimal? PayRate97 { get; set; }
        public decimal? PayRate98 { get; set; }
        public decimal? PayRate99 { get; set; }
        public decimal? PayRate100 { get; set; }
        public decimal? DailyRate1 { get; set; }
        public decimal? DailyRate2 { get; set; }
        public decimal? DailyRate3 { get; set; }
        public decimal? DailyRate4 { get; set; }
        public decimal? DailyRate5 { get; set; }
        public decimal? DailyRate6 { get; set; }
        public decimal? DailyRate7 { get; set; }
        public decimal? DailyRate8 { get; set; }
        public decimal? DailyRate9 { get; set; }
        public decimal? DailyRate10 { get; set; }
        public decimal? DailyRate11 { get; set; }
        public decimal? DailyRate12 { get; set; }
        public decimal? DailyRate13 { get; set; }
        public decimal? DailyRate14 { get; set; }
        public decimal? DailyRate15 { get; set; }
        public decimal? DailyRate16 { get; set; }
        public decimal? DailyRate17 { get; set; }
        public decimal? DailyRate18 { get; set; }
        public decimal? DailyRate19 { get; set; }
        public decimal? DailyRate20 { get; set; }
        public decimal? DailyRate21 { get; set; }
        public decimal? DailyRate22 { get; set; }
        public decimal? DailyRate23 { get; set; }
        public decimal? DailyRate24 { get; set; }
        public decimal? DailyRate25 { get; set; }
        public decimal? DailyRate26 { get; set; }
        public decimal? DailyRate27 { get; set; }
        public decimal? DailyRate28 { get; set; }
        public decimal? DailyRate29 { get; set; }
        public decimal? DailyRate30 { get; set; }
        public decimal? DailyRate31 { get; set; }
        public decimal? DailyRate32 { get; set; }
        public decimal? DailyRate33 { get; set; }
        public decimal? DailyRate34 { get; set; }
        public decimal? DailyRate35 { get; set; }
        public decimal? DailyRate36 { get; set; }
        public decimal? DailyRate37 { get; set; }
        public decimal? DailyRate38 { get; set; }
        public decimal? DailyRate39 { get; set; }
        public decimal? DailyRate40 { get; set; }
        public decimal? DailyRate41 { get; set; }
        public decimal? DailyRate42 { get; set; }
        public decimal? DailyRate43 { get; set; }
        public decimal? DailyRate44 { get; set; }
        public decimal? DailyRate45 { get; set; }
        public decimal? DailyRate46 { get; set; }
        public decimal? DailyRate47 { get; set; }
        public decimal? DailyRate48 { get; set; }
        public decimal? DailyRate49 { get; set; }
        public decimal? DailyRate50 { get; set; }
        public decimal? DailyRate51 { get; set; }
        public decimal? DailyRate52 { get; set; }
        public decimal? DailyRate53 { get; set; }
        public decimal? DailyRate54 { get; set; }
        public decimal? DailyRate55 { get; set; }
        public decimal? DailyRate56 { get; set; }
        public decimal? DailyRate57 { get; set; }
        public decimal? DailyRate58 { get; set; }
        public decimal? DailyRate59 { get; set; }
        public decimal? DailyRate60 { get; set; }
        public decimal? DailyRate61 { get; set; }
        public decimal? DailyRate62 { get; set; }
        public decimal? DailyRate63 { get; set; }
        public decimal? DailyRate64 { get; set; }
        public decimal? DailyRate65 { get; set; }
        public decimal? DailyRate66 { get; set; }
        public decimal? DailyRate67 { get; set; }
        public decimal? DailyRate68 { get; set; }
        public decimal? DailyRate69 { get; set; }
        public decimal? DailyRate70 { get; set; }
        public decimal? DailyRate71 { get; set; }
        public decimal? DailyRate72 { get; set; }
        public decimal? DailyRate73 { get; set; }
        public decimal? DailyRate74 { get; set; }
        public decimal? DailyRate75 { get; set; }
        public decimal? DailyRate76 { get; set; }
        public decimal? DailyRate77 { get; set; }
        public decimal? DailyRate78 { get; set; }
        public decimal? DailyRate79 { get; set; }
        public decimal? DailyRate80 { get; set; }
        public decimal? DailyRate81 { get; set; }
        public decimal? DailyRate82 { get; set; }
        public decimal? DailyRate83 { get; set; }
        public decimal? DailyRate84 { get; set; }
        public decimal? DailyRate85 { get; set; }
        public decimal? DailyRate86 { get; set; }
        public decimal? DailyRate87 { get; set; }
        public decimal? DailyRate88 { get; set; }
        public decimal? DailyRate89 { get; set; }
        public decimal? DailyRate90 { get; set; }
        public decimal? DailyRate91 { get; set; }
        public decimal? DailyRate92 { get; set; }
        public decimal? DailyRate93 { get; set; }
        public decimal? DailyRate94 { get; set; }
        public decimal? DailyRate95 { get; set; }
        public decimal? DailyRate96 { get; set; }
        public decimal? DailyRate97 { get; set; }
        public decimal? DailyRate98 { get; set; }
        public decimal? DailyRate99 { get; set; }
        public decimal? DailyRate100 { get; set; }
        public decimal? ChargeOutRate1 { get; set; }
        public decimal? ChargeOutRate2 { get; set; }
        public decimal? ChargeOutRate3 { get; set; }
        public decimal? ChargeOutRate4 { get; set; }
        public decimal? ChargeOutRate5 { get; set; }
        public decimal? ChargeOutRate6 { get; set; }
        public decimal? ChargeOutRate7 { get; set; }
        public decimal? ChargeOutRate8 { get; set; }
        public decimal? ChargeOutRate9 { get; set; }
        public decimal? ChargeOutRate10 { get; set; }
        public decimal? ChargeOutRate11 { get; set; }
        public decimal? ChargeOutRate12 { get; set; }
        public decimal? ChargeOutRate13 { get; set; }
        public decimal? ChargeOutRate14 { get; set; }
        public decimal? ChargeOutRate15 { get; set; }
        public decimal? ChargeOutRate16 { get; set; }
        public decimal? ChargeOutRate17 { get; set; }
        public decimal? ChargeOutRate18 { get; set; }
        public decimal? ChargeOutRate19 { get; set; }
        public decimal? ChargeOutRate20 { get; set; }
        public decimal? ChargeOutRate21 { get; set; }
        public decimal? ChargeOutRate22 { get; set; }
        public decimal? ChargeOutRate23 { get; set; }
        public decimal? ChargeOutRate24 { get; set; }
        public decimal? ChargeOutRate25 { get; set; }
        public decimal? ChargeOutRate26 { get; set; }
        public decimal? ChargeOutRate27 { get; set; }
        public decimal? ChargeOutRate28 { get; set; }
        public decimal? ChargeOutRate29 { get; set; }
        public decimal? ChargeOutRate30 { get; set; }
        public decimal? ChargeOutRate31 { get; set; }
        public decimal? ChargeOutRate32 { get; set; }
        public decimal? ChargeOutRate33 { get; set; }
        public decimal? ChargeOutRate34 { get; set; }
        public decimal? ChargeOutRate35 { get; set; }
        public decimal? ChargeOutRate36 { get; set; }
        public decimal? ChargeOutRate37 { get; set; }
        public decimal? ChargeOutRate38 { get; set; }
        public decimal? ChargeOutRate39 { get; set; }
        public decimal? ChargeOutRate40 { get; set; }
        public decimal? ChargeOutRate41 { get; set; }
        public decimal? ChargeOutRate42 { get; set; }
        public decimal? ChargeOutRate43 { get; set; }
        public decimal? ChargeOutRate44 { get; set; }
        public decimal? ChargeOutRate45 { get; set; }
        public decimal? ChargeOutRate46 { get; set; }
        public decimal? ChargeOutRate47 { get; set; }
        public decimal? ChargeOutRate48 { get; set; }
        public decimal? ChargeOutRate49 { get; set; }
        public decimal? ChargeOutRate50 { get; set; }
        public decimal? ChargeOutRate51 { get; set; }
        public decimal? ChargeOutRate52 { get; set; }
        public decimal? ChargeOutRate53 { get; set; }
        public decimal? ChargeOutRate54 { get; set; }
        public decimal? ChargeOutRate55 { get; set; }
        public decimal? ChargeOutRate56 { get; set; }
        public decimal? ChargeOutRate57 { get; set; }
        public decimal? ChargeOutRate58 { get; set; }
        public decimal? ChargeOutRate59 { get; set; }
        public decimal? ChargeOutRate60 { get; set; }
        public decimal? ChargeOutRate61 { get; set; }
        public decimal? ChargeOutRate62 { get; set; }
        public decimal? ChargeOutRate63 { get; set; }
        public decimal? ChargeOutRate64 { get; set; }
        public decimal? ChargeOutRate65 { get; set; }
        public decimal? ChargeOutRate66 { get; set; }
        public decimal? ChargeOutRate67 { get; set; }
        public decimal? ChargeOutRate68 { get; set; }
        public decimal? ChargeOutRate69 { get; set; }
        public decimal? ChargeOutRate70 { get; set; }
        public decimal? ChargeOutRate71 { get; set; }
        public decimal? ChargeOutRate72 { get; set; }
        public decimal? ChargeOutRate73 { get; set; }
        public decimal? ChargeOutRate74 { get; set; }
        public decimal? ChargeOutRate75 { get; set; }
        public decimal? ChargeOutRate76 { get; set; }
        public decimal? ChargeOutRate77 { get; set; }
        public decimal? ChargeOutRate78 { get; set; }
        public decimal? ChargeOutRate79 { get; set; }
        public decimal? ChargeOutRate80 { get; set; }
        public decimal? ChargeOutRate81 { get; set; }
        public decimal? ChargeOutRate82 { get; set; }
        public decimal? ChargeOutRate83 { get; set; }
        public decimal? ChargeOutRate84 { get; set; }
        public decimal? ChargeOutRate85 { get; set; }
        public decimal? ChargeOutRate86 { get; set; }
        public decimal? ChargeOutRate87 { get; set; }
        public decimal? ChargeOutRate88 { get; set; }
        public decimal? ChargeOutRate89 { get; set; }
        public decimal? ChargeOutRate90 { get; set; }
        public decimal? ChargeOutRate91 { get; set; }
        public decimal? ChargeOutRate92 { get; set; }
        public decimal? ChargeOutRate93 { get; set; }
        public decimal? ChargeOutRate94 { get; set; }
        public decimal? ChargeOutRate95 { get; set; }
        public decimal? ChargeOutRate96 { get; set; }
        public decimal? ChargeOutRate97 { get; set; }
        public decimal? ChargeOutRate98 { get; set; }
        public decimal? ChargeOutRate99 { get; set; }
        public decimal? ChargeOutRate100 { get; set; }
        public decimal? ChargeOutDailyRate1 { get; set; }
        public decimal? ChargeOutDailyRate2 { get; set; }
        public decimal? ChargeOutDailyRate3 { get; set; }
        public decimal? ChargeOutDailyRate4 { get; set; }
        public decimal? ChargeOutDailyRate5 { get; set; }
        public decimal? ChargeOutDailyRate6 { get; set; }
        public decimal? ChargeOutDailyRate7 { get; set; }
        public decimal? ChargeOutDailyRate8 { get; set; }
        public decimal? ChargeOutDailyRate9 { get; set; }
        public decimal? ChargeOutDailyRate10 { get; set; }
        public decimal? ChargeOutDailyRate11 { get; set; }
        public decimal? ChargeOutDailyRate12 { get; set; }
        public decimal? ChargeOutDailyRate13 { get; set; }
        public decimal? ChargeOutDailyRate14 { get; set; }
        public decimal? ChargeOutDailyRate15 { get; set; }
        public decimal? ChargeOutDailyRate16 { get; set; }
        public decimal? ChargeOutDailyRate17 { get; set; }
        public decimal? ChargeOutDailyRate18 { get; set; }
        public decimal? ChargeOutDailyRate19 { get; set; }
        public decimal? ChargeOutDailyRate20 { get; set; }
        public decimal? ChargeOutDailyRate21 { get; set; }
        public decimal? ChargeOutDailyRate22 { get; set; }
        public decimal? ChargeOutDailyRate23 { get; set; }
        public decimal? ChargeOutDailyRate24 { get; set; }
        public decimal? ChargeOutDailyRate25 { get; set; }
        public decimal? ChargeOutDailyRate26 { get; set; }
        public decimal? ChargeOutDailyRate27 { get; set; }
        public decimal? ChargeOutDailyRate28 { get; set; }
        public decimal? ChargeOutDailyRate29 { get; set; }
        public decimal? ChargeOutDailyRate30 { get; set; }
        public decimal? ChargeOutDailyRate31 { get; set; }
        public decimal? ChargeOutDailyRate32 { get; set; }
        public decimal? ChargeOutDailyRate33 { get; set; }
        public decimal? ChargeOutDailyRate34 { get; set; }
        public decimal? ChargeOutDailyRate35 { get; set; }
        public decimal? ChargeOutDailyRate36 { get; set; }
        public decimal? ChargeOutDailyRate37 { get; set; }
        public decimal? ChargeOutDailyRate38 { get; set; }
        public decimal? ChargeOutDailyRate39 { get; set; }
        public decimal? ChargeOutDailyRate40 { get; set; }
        public decimal? ChargeOutDailyRate41 { get; set; }
        public decimal? ChargeOutDailyRate42 { get; set; }
        public decimal? ChargeOutDailyRate43 { get; set; }
        public decimal? ChargeOutDailyRate44 { get; set; }
        public decimal? ChargeOutDailyRate45 { get; set; }
        public decimal? ChargeOutDailyRate46 { get; set; }
        public decimal? ChargeOutDailyRate47 { get; set; }
        public decimal? ChargeOutDailyRate48 { get; set; }
        public decimal? ChargeOutDailyRate49 { get; set; }
        public decimal? ChargeOutDailyRate50 { get; set; }
        public decimal? ChargeOutDailyRate51 { get; set; }
        public decimal? ChargeOutDailyRate52 { get; set; }
        public decimal? ChargeOutDailyRate53 { get; set; }
        public decimal? ChargeOutDailyRate54 { get; set; }
        public decimal? ChargeOutDailyRate55 { get; set; }
        public decimal? ChargeOutDailyRate56 { get; set; }
        public decimal? ChargeOutDailyRate57 { get; set; }
        public decimal? ChargeOutDailyRate58 { get; set; }
        public decimal? ChargeOutDailyRate59 { get; set; }
        public decimal? ChargeOutDailyRate60 { get; set; }
        public decimal? ChargeOutDailyRate61 { get; set; }
        public decimal? ChargeOutDailyRate62 { get; set; }
        public decimal? ChargeOutDailyRate63 { get; set; }
        public decimal? ChargeOutDailyRate64 { get; set; }
        public decimal? ChargeOutDailyRate65 { get; set; }
        public decimal? ChargeOutDailyRate66 { get; set; }
        public decimal? ChargeOutDailyRate67 { get; set; }
        public decimal? ChargeOutDailyRate68 { get; set; }
        public decimal? ChargeOutDailyRate69 { get; set; }
        public decimal? ChargeOutDailyRate70 { get; set; }
        public decimal? ChargeOutDailyRate71 { get; set; }
        public decimal? ChargeOutDailyRate72 { get; set; }
        public decimal? ChargeOutDailyRate73 { get; set; }
        public decimal? ChargeOutDailyRate74 { get; set; }
        public decimal? ChargeOutDailyRate75 { get; set; }
        public decimal? ChargeOutDailyRate76 { get; set; }
        public decimal? ChargeOutDailyRate77 { get; set; }
        public decimal? ChargeOutDailyRate78 { get; set; }
        public decimal? ChargeOutDailyRate79 { get; set; }
        public decimal? ChargeOutDailyRate80 { get; set; }
        public decimal? ChargeOutDailyRate81 { get; set; }
        public decimal? ChargeOutDailyRate82 { get; set; }
        public decimal? ChargeOutDailyRate83 { get; set; }
        public decimal? ChargeOutDailyRate84 { get; set; }
        public decimal? ChargeOutDailyRate85 { get; set; }
        public decimal? ChargeOutDailyRate86 { get; set; }
        public decimal? ChargeOutDailyRate87 { get; set; }
        public decimal? ChargeOutDailyRate88 { get; set; }
        public decimal? ChargeOutDailyRate89 { get; set; }
        public decimal? ChargeOutDailyRate90 { get; set; }
        public decimal? ChargeOutDailyRate91 { get; set; }
        public decimal? ChargeOutDailyRate92 { get; set; }
        public decimal? ChargeOutDailyRate93 { get; set; }
        public decimal? ChargeOutDailyRate94 { get; set; }
        public decimal? ChargeOutDailyRate95 { get; set; }
        public decimal? ChargeOutDailyRate96 { get; set; }
        public decimal? ChargeOutDailyRate97 { get; set; }
        public decimal? ChargeOutDailyRate98 { get; set; }
        public decimal? ChargeOutDailyRate99 { get; set; }
        public decimal? ChargeOutDailyRate100 { get; set; }
        public long? ExternalSiconTeamId { get; set; }
        public string? Rfidguid { get; set; }
        public bool? IsLocked { get; set; }
        public int? LoginAttempts { get; set; }
        public string? TwoFactorSecurityKey { get; set; }
        public string? AuthenticateGuid { get; set; }
        public int WorkPatternQtyTypeOverrideId { get; set; }
    }
}
