using System;
using System.Collections.Generic;

namespace MinimalApiTest.Domain.SageModels
{
    public partial class SiSmcase
    {
        public long SiSmcaseId { get; set; }
        public string? CaseNumber { get; set; }
        public long? SiSmdocumentStatusId { get; set; }
        public long? SiSmdocumentSubStatusId { get; set; }
        public long? SlcustomerAccountId { get; set; }
        public DateTime? CallDate { get; set; }
        public long? SiSmcaseTypeId { get; set; }
        public long? SiSmpriorityId { get; set; }
        public string? CreatedBy { get; set; }
        public long? SiSoprepeatContractId { get; set; }
        public long? SiconSubLocationId { get; set; }
        public long? CustDeliveryAddressId { get; set; }
        public long? SiconContactPersonId { get; set; }
        public string? Details { get; set; }
        public string? SpareText1 { get; set; }
        public string? SpareText2 { get; set; }
        public string? SpareText3 { get; set; }
        public string? SpareText4 { get; set; }
        public string? SpareText5 { get; set; }
        public string? LocationPostalName { get; set; }
        public string? LocationAddressLine1 { get; set; }
        public string? LocationAddressLine2 { get; set; }
        public string? LocationAddressLine3 { get; set; }
        public string? LocationAddressLine4 { get; set; }
        public string? LocationCity { get; set; }
        public string? LocationPostcode { get; set; }
        public string? AnalysisField1 { get; set; }
        public string? AnalysisField2 { get; set; }
        public string? AnalysisField3 { get; set; }
        public string? AnalysisField4 { get; set; }
        public string? AnalysisField5 { get; set; }
        public string? AnalysisField6 { get; set; }
        public long? SiSmslaid { get; set; }
        public string? AnalysisField7 { get; set; }
        public string? AnalysisField8 { get; set; }
        public string? AnalysisField9 { get; set; }
        public string? AnalysisField10 { get; set; }
        public string? AnalysisField11 { get; set; }
        public string? AnalysisField12 { get; set; }
        public string? AnalysisField13 { get; set; }
        public string? AnalysisField14 { get; set; }
        public string? AnalysisField15 { get; set; }
        public string? AnalysisField16 { get; set; }
        public string? AnalysisField17 { get; set; }
        public string? AnalysisField18 { get; set; }
        public string? AnalysisField19 { get; set; }
        public string? AnalysisField20 { get; set; }
        public long? BillingCustomerAccountId { get; set; }
        public bool? BoxSent { get; set; }
        public string? QuantityOfBoxesSent { get; set; }
        public long? SiJcRoleId { get; set; }
        public decimal? InsuranceClaimValue { get; set; }
        public decimal? InsuranceExcess { get; set; }
        public long? InsClaimCustomerAccountId { get; set; }
        public string? CancelReason { get; set; }
        public string? CustomerOrderNumber { get; set; }
        public long? SiconContractCoverTypeId { get; set; }
        public long? CaseOwnerSiJcRoleId { get; set; }
        public long? SiSmskillId { get; set; }
        public long? SiconContractId { get; set; }
        public long? SiconContractLineId { get; set; }
        public long? SiSmfaultCodeId { get; set; }
        public string? Solution { get; set; }
        public int? AppointmentNumberIncrementer { get; set; }
        public long? SiJcJobId { get; set; }
        public bool? NonContract { get; set; }
        public bool? PartsIncludedOnContract { get; set; }
        public bool? LabourIncludedOnContract { get; set; }
        public bool? TravelIncludedOnContract { get; set; }
        public decimal? TravelHoursIncludedOnContract { get; set; }
        public decimal? LabourDiscountPercOnContract { get; set; }
        public decimal? LabourHoursIncludedOnContract { get; set; }
        public decimal? PartsDiscountPercentOnContract { get; set; }
        public long? AssignedTo { get; set; }
        public long? LastTrackingStatus { get; set; }
        public bool? HasUnbookedTime { get; set; }
        public DateTime? CompletedDate { get; set; }
        public decimal? CalloutCharge { get; set; }
        public string? Summary { get; set; }
        public string? ContactName { get; set; }
        public string? ContactTelephone { get; set; }
        public string? ContactEmail { get; set; }
        public DateTime? NextAppointmentDate { get; set; }
        public string? NextAppointmentEngineer { get; set; }
        public bool? AllAppointmentsConfirmed { get; set; }
        public decimal? MaxSellingValue { get; set; }
        public long? ExternalTeamId { get; set; }
        public long? SlcustomerContactId { get; set; }
        public decimal? SubsequentCalloutCharge { get; set; }
        public long? BranchId { get; set; }
        public decimal? FirstHourRate { get; set; }
        public decimal? SubsequentHourRate { get; set; }
        public bool? OverrideLabourRates { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public decimal? FixedPriceValue { get; set; }
        public bool? UseFixedPrice { get; set; }
        public bool? FixedPriceCharged { get; set; }
        public long? FixedPriceStockItemId { get; set; }
        public bool? ExpensesIncluded { get; set; }
        public decimal? ExpenseMarkup { get; set; }
        public decimal? MaxTravelChargeHours { get; set; }
        public bool? HalfHourPeriodForLabOverride { get; set; }
        public long? SiSmcaseSummaryOptionId { get; set; }
        public long? SiSmcaseSolutionOptionId { get; set; }
        public long? FixedPriceRevenueSiJcTrnId { get; set; }
        public long? SoporderReturnContractLineId { get; set; }
        public string? LocationCounty { get; set; }
        public long? WorkPatternOverrideId { get; set; }
        public decimal? MileageChargeRate { get; set; }
        public DateTime? LastAttachmentUpdate { get; set; }
        public int? CurrentSlastate { get; set; }
        public string? AssignedToUserName { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? WarningDate { get; set; }
        public DateTime? FirstReturnDate { get; set; }
        public long? StockItem { get; set; }
        public bool? IsPreventativeMaintenance { get; set; }
        public long? OwnerSiconContactPersonId { get; set; }
        public long? SiconCrmpersonId { get; set; }
        public long? SiconCrmpersonEndUserId { get; set; }
        public long? SiconCrmcompanyId { get; set; }
        public long? SiconCrmcompanyEndUserId { get; set; }
        public bool? PreferEndUserContact { get; set; }
        public long? SiSmcaseTrackingNoteId { get; set; }
    }
}
