namespace MinimalApiTest.Domain.Models
{
    public partial class ConstructionApplication
    {
        public long ConstructionApplicationId { get; set; }
        public long? SageDatabaseId { get; set; }
        public long? InvoiceUrn { get; set; }
        public long? SupplierId { get; set; }
        public long? CustomerId { get; set; }
        public long? ProjectItemId { get; set; }
        public long? SysaccountingPeriodId { get; set; }
        public long? SysfinancialYearId { get; set; }
        public long? AccountingPeriod { get; set; }
        public long? AccountingPeriodYear { get; set; }
        public long? SoporderReturnLineId { get; set; }
        public long? LastUpdatedByUserId { get; set; }
        public long? Retention1Id { get; set; }
        public long? Retention2Id { get; set; }
        public long? Retention3Id { get; set; }
        public long? Retention4Id { get; set; }
        public long? TaxCodeId { get; set; }
        public string? ApplicationType { get; set; }
        public string? ApplicationRef { get; set; }
        public string? ApplicationRef2 { get; set; }
        public string? SupplierReference { get; set; }
        public string? CustomerReference { get; set; }
        public string? ApplicationStatus { get; set; }
        public string? InvoiceReference { get; set; }
        public string? JobNumber { get; set; }
        public string? CostCode { get; set; }
        public string? ApplicationNo { get; set; }
        public string? Queried { get; set; }
        public string? Note { get; set; }
        public long? SijcempId { get; set; }
        public string? JobManager { get; set; }
        public decimal? ApplicationAppliedFor { get; set; }
        public decimal? ApplicationValued { get; set; }
        public decimal? ApplicationInvoiced { get; set; }
        public decimal? AppliedForQuantity { get; set; }
        public decimal? ValuedQuantity { get; set; }
        public decimal? RiskValue { get; set; }
        public decimal? RetentionPercentage1 { get; set; }
        public decimal? RetentionPercentage2 { get; set; }
        public decimal? RetentionPercentage3 { get; set; }
        public decimal? RetentionPercentage4 { get; set; }
        public decimal? OpeningBalance { get; set; }
        public decimal? RetentionTotal { get; set; }
        public decimal? OpeningBalanceRet { get; set; }
        public decimal? OpeningBalanceNet { get; set; }
        public decimal? ApplicationInvoicedRet { get; set; }
        public decimal? ApplicationReceivedRet { get; set; }
        public decimal? ApplicationReceived { get; set; }
        public decimal? DiscountPercent { get; set; }
        public decimal? DiscountValue { get; set; }
        public decimal? SiJctrnApplicationGross { get; set; }
        public decimal? SiJctrnDicount { get; set; }
        public decimal? ApplicationAppliedForNet { get; set; }
        public decimal? ApplicationValuedNet { get; set; }
        public decimal? ApplicationInvoicedNet { get; set; }
        public decimal? ApplicationReceivedNet { get; set; }
        public decimal? ApplicationTax { get; set; }
        public decimal? ApplicationTaxNet { get; set; }
        public DateTime? ApplicationDate { get; set; }
        public DateTime? ApplicationValuedDate { get; set; }
        public DateTime? ApplicationPostedDate { get; set; }
        public DateTime? LastUpdatedByDateTime { get; set; }
        public DateTime? ApplicationExpiryDate { get; set; }
        public DateTime? ValuationDate { get; set; }
        public DateTime? PayLessDate { get; set; }
        public DateTime? PaymentDueDate { get; set; }
        public DateTime? RetentionDate1 { get; set; }
        public DateTime? RetentionDate2 { get; set; }
        public DateTime? RetentionDate3 { get; set; }
        public DateTime? RetentionDate4 { get; set; }
        public bool? Despatched { get; set; }
        public bool? IsFinal { get; set; }
        public bool? Deleted { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? UpdatedUser { get; set; }
        public string? DocumentStatus { get; set; }
        public string? UpdateStatus { get; set; }
        public long? RequestedById { get; set; }
        public string? RequestedByName { get; set; }
        public bool? Posted { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime? FullyApprovedDate { get; set; }
        public bool? Urgent { get; set; }
        public string? UrgentReason { get; set; }
        public string? LineStatus { get; set; }
        public string? RejectReason { get; set; }
        public long? CurrentStep { get; set; }
        public bool? CustomRoute { get; set; }
        public long? CustomRouteId { get; set; }
        public long? CurrentStepApprovalCount { get; set; }
        public bool? Submitted { get; set; }
        public bool? OverBudget { get; set; }
        public bool ResetRoute { get; set; }
        public DateTime? SubmittedDate { get; set; }
        public long? FinanceCharge { get; set; }
        public long? SageApplicationId { get; set; }
        public bool LinesToProcess { get; set; }
    }
}
