namespace MinimalApiTest.Domain.Models
{
    public partial class Sage50PurchaseLedger
    {
        public long Sage50PurchaseLedgerId { get; set; }
        public string? AccountRef { get; set; }
        public string? Name { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public string? Address3 { get; set; }
        public string? Address4 { get; set; }
        public string? Address5 { get; set; }
        public string? CAddress1 { get; set; }
        public string? CAddress2 { get; set; }
        public string? CAddress3 { get; set; }
        public string? CAddress4 { get; set; }
        public string? CAddress5 { get; set; }
        public string? ContactName { get; set; }
        public string? Telephone { get; set; }
        public string? Telephone2 { get; set; }
        public string? Fax { get; set; }
        public string? EMail { get; set; }
        public string? WebAddress { get; set; }
        public string? TradeContact { get; set; }
        public string? DelName { get; set; }
        public string? DelAddress1 { get; set; }
        public string? DelAddress2 { get; set; }
        public string? DelAddress3 { get; set; }
        public string? DelAddress4 { get; set; }
        public string? DelAddress5 { get; set; }
        public string? DelContactName { get; set; }
        public string? DelTelephone { get; set; }
        public string? DelFax { get; set; }
        public string? Analysis1 { get; set; }
        public string? Analysis2 { get; set; }
        public string? Analysis3 { get; set; }
        public short? DeptNumber { get; set; }
        public string? DeptName { get; set; }
        public short? StatusNumber { get; set; }
        public string? StatusText { get; set; }
        public string? DefTaxCode { get; set; }
        public string? DefNomCode { get; set; }
        public string? VatRegNumber { get; set; }
        public short? Currency { get; set; }
        public string? CountryCode { get; set; }
        public decimal? DiscountRate { get; set; }
        public decimal? SettlementDiscRate { get; set; }
        public short? SettlementDueDays { get; set; }
        public short? PaymentDueDays { get; set; }
        public decimal? CreditLimit { get; set; }
        public short? AccountOnHold { get; set; }
        public string? Terms { get; set; }
        public short? RestrictMail { get; set; }
        public short? TermsAgreed { get; set; }
        public DateTime? DateAccountOpened { get; set; }
        public DateTime? DateNextCredit { get; set; }
        public DateTime? DateLastCredit { get; set; }
        public string? CreditPosition { get; set; }
        public short? CreditPosCode { get; set; }
        public short? UseBacs { get; set; }
        public short? UseBsoc { get; set; }
        public string? BacsRef { get; set; }
        public short? BureauCode { get; set; }
        public string? CreditRef { get; set; }
        public DateTime? DateCreditApplied { get; set; }
        public DateTime? DateCreditReceived { get; set; }
        public short? OverrideTaxCode { get; set; }
        public DateTime? LastPaymentDate { get; set; }
        public DateTime? FirstInvDate { get; set; }
        public DateTime? LastInvDate { get; set; }
        public decimal? Balance { get; set; }
        public decimal? TurnoverMtd { get; set; }
        public decimal? TurnoverYtd { get; set; }
        public decimal? PriorYear { get; set; }
        public string? BankName { get; set; }
        public string? BankAddress1 { get; set; }
        public string? BankAddress2 { get; set; }
        public string? BankAddress3 { get; set; }
        public string? BankAddress4 { get; set; }
        public string? BankAddress5 { get; set; }
        public string? BankSortCode { get; set; }
        public string? BankAccountName { get; set; }
        public string? BankAccountNumber { get; set; }
        public string? BankIban { get; set; }
        public string? BankBic { get; set; }
        public string? BankRollnumber { get; set; }
        public string? BankAdditionalref1 { get; set; }
        public string? BankAdditionalref2 { get; set; }
        public string? BankAdditionalref3 { get; set; }
        public long? DefaultFundId { get; set; }
        public decimal? InvoiceBf { get; set; }
        public decimal? InvoiceMth1 { get; set; }
        public decimal? InvoiceMth2 { get; set; }
        public decimal? InvoiceMth3 { get; set; }
        public decimal? InvoiceMth4 { get; set; }
        public decimal? InvoiceMth5 { get; set; }
        public decimal? InvoiceMth6 { get; set; }
        public decimal? InvoiceMth7 { get; set; }
        public decimal? InvoiceMth8 { get; set; }
        public decimal? InvoiceMth9 { get; set; }
        public decimal? InvoiceMth10 { get; set; }
        public decimal? InvoiceMth11 { get; set; }
        public decimal? InvoiceMth12 { get; set; }
        public decimal? InvoiceCf { get; set; }
        public decimal? CreditBf { get; set; }
        public decimal? CreditMth1 { get; set; }
        public decimal? CreditMth2 { get; set; }
        public decimal? CreditMth3 { get; set; }
        public decimal? CreditMth4 { get; set; }
        public decimal? CreditMth5 { get; set; }
        public decimal? CreditMth6 { get; set; }
        public decimal? CreditMth7 { get; set; }
        public decimal? CreditMth8 { get; set; }
        public decimal? CreditMth9 { get; set; }
        public decimal? CreditMth10 { get; set; }
        public decimal? CreditMth11 { get; set; }
        public decimal? CreditMth12 { get; set; }
        public decimal? CreditCf { get; set; }
        public decimal? PaymentBf { get; set; }
        public decimal? PaymentMth1 { get; set; }
        public decimal? PaymentMth2 { get; set; }
        public decimal? PaymentMth3 { get; set; }
        public decimal? PaymentMth4 { get; set; }
        public decimal? PaymentMth5 { get; set; }
        public decimal? PaymentMth6 { get; set; }
        public decimal? PaymentMth7 { get; set; }
        public decimal? PaymentMth8 { get; set; }
        public decimal? PaymentMth9 { get; set; }
        public decimal? PaymentMth10 { get; set; }
        public decimal? PaymentMth11 { get; set; }
        public decimal? PaymentMth12 { get; set; }
        public decimal? PaymentCf { get; set; }
        public long? SageDatabaseId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? UpdatedUser { get; set; }
        public bool Deleted { get; set; }
    }
}
