namespace MinimalApiTest.Domain.Models
{
    public partial class SalesOrder
    {
        public long SalesOrderId { get; set; }
        public long? SlcustomerAccountId { get; set; }
        public string? Special { get; set; }
        public long? RequestedByUserId { get; set; }
        public bool? Urgent { get; set; }
        public string? OrderStatus { get; set; }
        public DateTime? OrderDate { get; set; }
        public bool? Deleted { get; set; }
        public bool? SentToSage { get; set; }
        public long? SoporderReturnId { get; set; }
        public long? SageDatabaseId { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? RequestedDeliveryDate { get; set; }
        public string? CustomerReference { get; set; }
        public string? Analysis1 { get; set; }
        public string? Analysis2 { get; set; }
        public string? Analysis3 { get; set; }
        public string? Analysis4 { get; set; }
        public string? Analysis5 { get; set; }
        public string? Analysis6 { get; set; }
        public string? Analysis7 { get; set; }
        public string? Analysis8 { get; set; }
        public string? Analysis9 { get; set; }
        public string? Analysis10 { get; set; }
        public string? Analysis11 { get; set; }
        public string? Analysis12 { get; set; }
        public string? Analysis13 { get; set; }
        public string? Analysis14 { get; set; }
        public string? Analysis15 { get; set; }
        public string? Analysis16 { get; set; }
        public string? Analysis17 { get; set; }
        public string? Analysis18 { get; set; }
        public string? Analysis19 { get; set; }
        public string? Analysis20 { get; set; }
        public decimal? OrderDiscount { get; set; }
        public decimal? OrderDiscountPercent { get; set; }
        public string? SageDatabaseName { get; set; }
        public string? CustomerName { get; set; }
        public string? RequestedByUserName { get; set; }
        public string? DeliveryAddressName { get; set; }
        public decimal? NetValue { get; set; }
        public long? DepartmentId { get; set; }
        public string? SodocumentNo { get; set; }
        public bool? Archived { get; set; }
        public string? UpdateStatus { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? UpdatedUser { get; set; }
        public long? WarehouseId { get; set; }
        public decimal? ExchangeRate { get; set; }
        public string? CurrencySymbol { get; set; }
        public string? CustomerEmailAddress { get; set; }
        public string? CustomerContactName { get; set; }
        public string? CustomerTelephone { get; set; }
        public string? CustomerFax { get; set; }
        public bool? HasAttachments { get; set; }
        public bool? HasAnalysisValues { get; set; }
        public long? SystraderAnalysisValueId { get; set; }
        public bool? InternalOrder { get; set; }
        public bool? UseInvoiceAddress { get; set; }
        public string? DeliveryPostalName { get; set; }
        public string? DeliveryAddressLine1 { get; set; }
        public string? DeliveryAddressLine2 { get; set; }
        public string? DeliveryAddressLine3 { get; set; }
        public string? DeliveryAddressLine4 { get; set; }
        public string? DeliveryCity { get; set; }
        public string? DeliveryCounty { get; set; }
        public string? DeliveryPostCode { get; set; }
        public string? InvoicePostalName { get; set; }
        public string? InvoiceAddressLine1 { get; set; }
        public string? InvoiceAddressLine2 { get; set; }
        public string? InvoiceAddressLine3 { get; set; }
        public string? InvoiceAddressLine4 { get; set; }
        public string? InvoicePostCode { get; set; }
        public string? InvoiceCity { get; set; }
        public string? InvoiceCounty { get; set; }
        public bool? CheckForNewDocuments { get; set; }
        public string? SalesOrderType { get; set; }
        public string? Crmusername { get; set; }
        public decimal? TradeInValue { get; set; }
        public decimal? AmountPaid { get; set; }
        public long? VersionNumber { get; set; }
        public long? CustomerDeliveryAddressId { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public long? PaymentType { get; set; }
        public bool? SalesOrderGenerated { get; set; }
        public long? ConvertedFromQuote { get; set; }
        public long? CrmcompanyId { get; set; }
        public bool? Submitted { get; set; }
        public string? ErrorMessage { get; set; }
        public bool? ProFormaPrinted { get; set; }
        public bool? QuotePrinted { get; set; }
        public bool? SalesOrderPrinted { get; set; }
        public bool? SalesOrderInternalPrinted { get; set; }
        public DateTime? FullyApprovedDate { get; set; }
        public string? UrgentReason { get; set; }
        public long? SysCountryCodeId { get; set; }
        public long? SysTaxCodeId { get; set; }
        public string? TaxNumber { get; set; }
        public DateTime? SubmittedDate { get; set; }
        public string? QuoteStatus { get; set; }
        public string? MobileGuid { get; set; }
        public bool? MandatoryCustom1 { get; set; }
        public bool? MandatoryCustom2 { get; set; }
        public bool? MandatoryCustom3 { get; set; }
        public long? LinkedSalesOrderId { get; set; }
        public long? LinkedSopreturnId { get; set; }
        public string? LinkedSalesOrderDocumentNo { get; set; }
        public string? SpareText1 { get; set; }
        public string? SpareText2 { get; set; }
        public string? SpareText3 { get; set; }
        public DateTime? SpareDate1 { get; set; }
        public DateTime? SpareDate2 { get; set; }
        public DateTime? SpareDate3 { get; set; }
        public bool SpareBit1 { get; set; }
        public bool SpareBit2 { get; set; }
        public bool SpareBit3 { get; set; }
        public decimal? SpareNumber1 { get; set; }
        public decimal? SpareNumber2 { get; set; }
        public decimal? SpareNumber3 { get; set; }
    }
}
