namespace MinimalApiTest.Domain.Models
{
    public partial class SalesOrderLine
    {
        public long SalesOrderLineId { get; set; }
        public long? SalesOrderId { get; set; }
        public decimal? Quantity { get; set; }
        public string? Description { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? UnitCost { get; set; }
        public decimal? Discount { get; set; }
        public long? NlnominalAccountId { get; set; }
        public bool? Deleted { get; set; }
        public string? LineStatus { get; set; }
        public bool? SentToSage { get; set; }
        public decimal? TotalPrice { get; set; }
        public string? LineType { get; set; }
        public long? ProjectCodeId { get; set; }
        public long? ProjectItemId { get; set; }
        public long? ProjectPhaseId { get; set; }
        public long? ProjectStageId { get; set; }
        public long? ProjectSubStageId { get; set; }
        public long? ProjectVariationId { get; set; }
        public long? SoporderReturnLineId { get; set; }
        public long? StockItemId { get; set; }
        public long? SageDatabaseId { get; set; }
        public string? ItemCode { get; set; }
        public long? TaxCodeId { get; set; }
        public long? WarehouseId { get; set; }
        public int? CurrentStep { get; set; }
        public decimal? QuantityDespatched { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? UpdatedUser { get; set; }
        public bool? ShowCommentOnCustomerDocs { get; set; }
        public string? PricingUnitDescription { get; set; }
        public string? SellingUnitDescription { get; set; }
        public decimal? SellingMultOfStockUnit { get; set; }
        public decimal? PricingMultOfStockUnit { get; set; }
        public DateTime? RequestedDeliveryDate { get; set; }
        public bool? CustomRoute { get; set; }
        public long? CustomRouteId { get; set; }
        public string? RejectReason { get; set; }
        public long? CurrentStepApprovalCount { get; set; }
        public decimal? QuantityInvoiced { get; set; }
        public bool? Submitted { get; set; }
        public bool? AmendedDescription { get; set; }
        public string? AmendedDescriptionText { get; set; }
        public string? Analysis1 { get; set; }
        public string? Analysis2 { get; set; }
        public string? Analysis3 { get; set; }
        public string? Analysis4 { get; set; }
        public string? Analysis5 { get; set; }
        public string? Analysis6 { get; set; }
        public string? Analysis7 { get; set; }
        public string? Analysis8 { get; set; }
        public string? Analysis9 { get; set; }
        public string? Analysis10 { get; set; }
        public string? Analysis11 { get; set; }
        public string? Analysis12 { get; set; }
        public string? Analysis13 { get; set; }
        public string? Analysis14 { get; set; }
        public string? Analysis15 { get; set; }
        public string? Analysis16 { get; set; }
        public string? Analysis17 { get; set; }
        public string? Analysis18 { get; set; }
        public string? Analysis19 { get; set; }
        public string? Analysis20 { get; set; }
        public int? FulfilmentMethodId { get; set; }
        public long? DeliveryAddressId { get; set; }
        public decimal? SopunitPrice { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public int? ContractDuration { get; set; }
        public DateTime? BillCoverFrom { get; set; }
        public DateTime? BillCoverTo { get; set; }
        public int? BillCoverDuration { get; set; }
        public int? InvoiceFrequency { get; set; }
        public bool? ProRata { get; set; }
        public bool? Complimentary { get; set; }
        public string? CustomerCode { get; set; }
        public int? InitialContractDuration { get; set; }
        public DateTime? ProRataDate { get; set; }
        public long? Ordinal { get; set; }
        public long? StockItemSupplierId { get; set; }
        public decimal? MarginPercent { get; set; }
        public string? ErrorMessage { get; set; }
        public long? PostedCostingDetailId { get; set; }
        public bool ResetRoute { get; set; }
        public bool OverBudget { get; set; }
        public long? IssuesNominalAccountId { get; set; }
        public long? LineNumber { get; set; }
        public string? MobileGuid { get; set; }
        public string? JobManager { get; set; }
        public string? SpareText1 { get; set; }
        public string? SpareText2 { get; set; }
        public string? SpareText3 { get; set; }
        public DateTime? SpareDate1 { get; set; }
        public DateTime? SpareDate2 { get; set; }
        public DateTime? SpareDate3 { get; set; }
        public bool SpareBit1 { get; set; }
        public bool SpareBit2 { get; set; }
        public bool SpareBit3 { get; set; }
        public decimal? SpareNumber1 { get; set; }
        public decimal? SpareNumber2 { get; set; }
        public decimal? SpareNumber3 { get; set; }
        public string? SalesOrderType { get; set; }
    }
}
